### ISSUE TITLE
2024 Q1 Event - Logistics - Check-in

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#12]
[Pilot event notes](https://docs.google.com/document/d/106st3E4nNViZhedZ6N2ZJE9W0J_wvN0-0VmZjQftio0/edit#heading=h.plt13akfxp0s) include a list of specific tasks and ideas:

## Tasks (At the Event Venue)
- [ ] Setup a check-in table with pre-printed name tags (Jim will bring name tags)
- [ ] Setup extra, blank name tag sheets and colored marker. Be sure the markers don’t bleed through to the surface below.
- [ ] Setup the three small HackGreenville "neons" with extension cord (located in OW on top of the book shelf)
- [ ] Load digital schedule / sponsor graphic and connect it to the kitchen TV (computer w/ HDMI required  - Jim can bring one if needed)
- [ ] Setup any directional signage, doorbells, etc at check-in and entrances.
  - [ ] Don’t put tape on any wall surfaces that may be damaged when the tape is removed
  - [ ] Put the doorbell buttons on the deck entrances low enough that someone in a wheelchair can see and press the button
- [ ] Assign someone as a greeter / door opener for the **parking deck** entrances since they can’t be unlocked besides when someone inside triggers the door to open
- [ ] Assign volunteer greeter(s) to monitor the lobby and let the guests into the elevator from 6:00 PM - 6:10 PM
- [ ] Assign temporary key fobs to any lobby greeters, or other volunteers who may need one
- [ ] Hang restroom, guest Wi-Fi, or any other directional signage. Try to put tape on the back of any signs that we might want to reuse for future events.
- [ ] Mark or highlight the attendance as people arrive
- [ ] Write walk-in attendees info, if they are willing to share, and encourage them to join the Meetup Group or RSVP on their phone
- Security
  - [ ] Before the event starts, give any security guards a heads-up to expect guests
  - [ ] Offer the security guard food
  - [ ] Confirm with security guard if they will be at the desk after 6 PM. If not, confirm that it's alright to but a sign on the front door directing guests to the parking deck entrance
