### ISSUE TITLE
2024 Q2 Event - Food & Drink Planning

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#17]
### Notes
In February 2024, we had 5 out of 75 attendees indicate a dietary allergy / constraint, including: peanut, pecan, dairy, vegan, and vegetarian concerns. This confirms we should avoid some ingredients, or else have at least one option which will satisfy these types of concerns.

### Menu
- [Publix Cubanitos (~ 25 people) and Veggie Wrap Platter (~ 8 people)](https://www.publix.com/mc/order-ahead/landing) - Eric
- [Ham Sliders](https://www.allrecipes.com/recipe/216756/baked-ham-and-cheese-party-sandwiches/) - Jim (~ 15 people)
- Swamp Rabbit Cafe Stecca Bread - Jim - probably about 8 loaves
- [Mexican Bean Dip](https://github.com/hackgvl/nights/issues/17#issuecomment-2102801492) and Tortilla Chips - Jim
- Chicken Salad and Curry Chicken Salad to top sliced stecca (JIM WILL GET THE STECCA) - Joel - 2 lbs of each
- Savory and non-Savory Spreads to top sliced stecca (JIM WILL GET THE STECCA) - Brian - enough to feed about 15 people 

### Future Ideas

- Potato Bar
- Soups
- See [Joel's link to a Reddit Thread](https://github.com/hackgvl/nights/issues/17#issuecomment-2098306696)

### Food Volunteers
sirbeep - Brian Kennedy
eric-hemasystems - Eric Anderson
allella - Jim Ciallella
TwonkyHardware - Joel Griffith

### Hot Plates / Slow Cookers
If we need these to keep things warm, then people offered.
- sirbeep - dual hot plate
- @ThorntonMatthewD - has a couple of slow cookers and a hot plate

### Budget

- We agreed to provide a set amount per batch, and assuming it will feed a specific number of people
- [Jim suggested catering and recipes can typically be cut by 25-40%](https://hackgreenville.slack.com/archives/C0JPADQDD/p1706472825699389?thread_ts=1706289280.129669&cid=C0JPADQDD)
- The [SnackGreenville document](https://docs.google.com/document/d/1ZBEl61eH4kB6NVHqjrlEgnYyRrfONAyJoQXFcH5muaQ/edit#heading=h.374owrq3m4r2) has recent history, including the prices and amounts used for the HG Nights pilot taco bar.
- $20 to $25 per 10 person batch is what sounds reasonable
- Best guess at this point is we'll have 50-80 people register for the event and not everyone will eat
- Volunteers will likely be reimbursed through _[Expensify](https://www.expensify.com/)_. We might expect this to be paid before the event, as long as the sponsor funds are deposited well enough in advance to make it happen.

### Other Food and Desserts
- Toppings
- We did an easy and cheap dessert handout about 15-20 minutes before the wrap-up event with ice cream sandwiches and thanked the physical location host (OpenWorks) for hosting. People seemed to enjoy it, though some people had already left, so we didn't need 1 per person
- Beer - For the pilot this was a perk for volunteers.  Given the liability and added cost, this could remain a volunteer-only perk

### Drinks
- Canned drinks seem to work best and can be recycled at OpenWorks
- Refrigerating the drinks in advance and setting them out in the retail boxes seems to work well
- Sparkling Water - we have some left over from the last event.
- Soda - We have some left over from the last event
- Bottled water - We have some left over from the last event

### Tasks (In-advance)
- [x] Put out a call for volunteers (as w/ (https://hackgreenville.slack.com/archives/C0JPADQDD/p1706289280129669))
- [x] Dietary or allergy considerations - check to registration form responses
- [x] Instruct volunteers to save any receipts for reimbursement
- [x] Gather recipe ingredients so they can be printed on signs for allergy considerations
- [x] Pay for any prepared food from vendors, either in advance, or at pickup. 
- [x] Check the vendor's hours of operation and pick-up details in advance
- [x] Communicate with volunteers
- [x] Designate a reliable pick-up person and share the pick-up time and details of how to unload the food at the venue
- [x] Determine if drinks can be refrigerated in advance, or if ice and ice bins are needed. - Jim has some 6" tall plastic totes which we've used in the past to ice drinks, and they could be used upon request.
- [x] Determine if any prepared food needs to be refrigerated and confirm there is space - OpenWorks has a large and small refrigerator and there is typically space as long as the refrigerators have been cleaned out of old stuff
- [x] Determine if a freezer is needed and available at the venue. - OpenWorks has a very small freezer, so we'd definitely need to verify space in advance.
- [x] Purchase any food, drinks, plates, napkins, etc in advance
- [x] Purchase volunteer beer and any special volunteer snacks.  A 15 mix pack of Oskar Blues beer is usually enough. 
- [x] Reimburse any volunteers for budgeted food costs

### Tasks (At the Event Venue)
- [ ] Prepare any food that’s being made on-site
- [ ] Setup food, serving bowls, serving utensils (spoons, tongs). Setup TWO serving utensils for EACH of the main dishes so people can serve from both sides of the bar.
- [ ] Setup bowls / plates at check-in table so people need to check-in before they can eat.
- [ ] Setup napkins, forks / spoons at the end of the food line / upper bar, so people don't have to hold these things while they are making a plate
- [ ] Put forks or spoons in a container, like a mason jar, or small bowl, with the handles facing up / out so people can grab them by the handle.
- [ ] Avoid putting any very hot items directly on the wood counter tops. Use a trivet or other something under hot items. 
- [ ] Move the trash and recycling cans out of the way, but still in a visible spot.
- [ ] Setup a bus bucket near the trash cans for dirty utensils / dishes
- [ ] Setup any food heating (ovens, crockpots, hot plates, microwave) or chilling equipment using heavy power cords if needed and try to not put everything on the same circuit, if / when it's possible to tell.
- [ ] Setup drinks, ice, cups on a rolling table at the very end of the food line, or even near the check-in, so people aren't trying to hold a drink while they are making a plate. We'll likely roll this drink table out of the kitchen and into OpenWorks' Social Lounge for the later half of the event.
  - Cans
    1. [ ] Setup cans - Ideally, keep cans in the cardboard boxes and open 1/2 of one end of the box and put something under the rear of the box so the cans roll forward to the opening for easy grabbing.
    1. [ ] Otherwise, if cans are not cold then it may not be necessary to ice them down in a bin.
    - Note: If icing down the cans, put cans into any bins before pouring the ice on top. Otherwise, it’s very hard to put the cans into shallow ice.
    - Note: Icing cans will often cause condensation, so putting a towel or thick piece of cardboard under the cold bin can help insulate the bottom and limit a wet mess
  - [ ] If using 2-liters, then setup the bottles and cups - (Note: OpenWorks has a bunch of small foam cups in the lower cabinets opposite the bar stools)
  - [ ] (Optionally) Setup clean ice bucket w/ drinking ice & tongs - ideally this isn't needed when serving refrigerated cans
- [ ] When the line forms, encourage people to use both sides of the bar to double the throughput of the main course.

**Comment by allella** [comment]
Ideas from Eric
![image](https://github.com/hackgvl/nights/assets/1777776/e5113bd6-b189-4a17-a260-d5808ab5f365)

**Comment by allella** [comment]
Another idea for food would be a premium salad bar.  Like, not all lettuce salads, but that could be and option.
Sort of like Ruby Tuesdays, but with unique dishes. For instance, my wife has a bean, pepper, tomato salad that goes with tortilla chips that's always a hit.

Perhaps have some extras / add-ons like meats or bacon.  So, perhaps not unlike the potato bar, but using salads as a base.

**Comment by allella** [comment]
## Call for Volunteers
@sirbeep @eric-hemasystems @TwonkyHardware no pressure, but I think we had a great food experience at the last event and it would be great to have all of you, and Alice, continue to chip in your talents as time allows.

## Food Ideas
It would be great to hear thoughts on food for the May event and any other bright ideas for original concepts for this event, or figure events.  For example, it may have mentioned soup to do soups for a future winter event.

We're way ahead of the game on most fronts based [on our project view](https://github.com/orgs/hackgvl/projects/6/views/2), so we don't have to cram as much into the final month, like we did on the [last event](https://github.com/orgs/hackgvl/projects/6/views/1).

### Potato Bar Idea
Eric's idea of a potato bar is an interesting one, but I'm not sure of the logistics of baking 60+ potatoes and keeping them warm enough to be good.  Someone mentioned you can cook potatoes in a crock pot, though I'm not sure that's as practical for cooking many potatoes as helping keep them warm.  My convection oven would probably only fit 20-25 potatoes if we wanted to serve them hot. 

### Salad Salad Bar Idea
The potato idea got me thinking about having lots of toppings and that triggered the earlier comment about a "[Salad Salad Bar](https://github.com/hackgvl/nights/issues/17#issuecomment-2045810763)".  Like, different protein and side salads (chicken, ham, egg salad, potato?, etc) could be put on top of a bed of lettuces, and/or eaten alone.

### Food Preferences
I think about 60 of 75 people actually ate a the chili event. Pam said some people had already eaten, were planning to eat later, or didn't like chili.  That last part gives me some question about how many people would be excited about the potato base, since we'd not really have much else for them to eat besides topping.  With a salad bar, presumably most people could find something they'd enjoy.

We could certainly put a poll on the Slack if we want to gauge interest between ideas.

## Budget
We have at least a few hundred dollars to cover food and drink costs and reimburse everyone.  The [sponsorship](https://github.com/hackgvl/meta/issues/23) was for four hundred, but after Stripe takes a cut, we lose some of that budget right off the bat.  

I'm also hoping we can continue to spend a small amount on non-disposable improvements, like possibly getting decent plates or bowls as we go, as we've already done with the reusable forks and spoons.

## Homemade Touch vs Easy Button
I realize it's work to prepare things, but I'm still excited to come up with original ideas and homemade touch that folks aren't going to find at other events.

We obviously made everything from scratch at the chili event.  The middle-ground, as we did for the taco night, is to purchase quality, made-fresh proteins and build around that with topics, sides, or preparations (wraps, breads).  So, that's certainly an option as long as we can stay in budget.

I'm less excited about full-on outsourcing the food prep to a company if we can keep having fun with it and keep the volunteer interest we've had in the prior events.

## Reimbursement as the Norm
I believe most, or all, of you didn't ask for reimbursement on the [chili night](https://github.com/hackgvl/nights/issues/2).  

That's certainly not the expectation, so please expect the norm to be that volunteers are donating their time and craft and not  expected to come out of pocket, too.

**Comment by sirbeep** [comment]
Eh.  On reimbursement, I buy beef
![PXL_20240329_174814247 MP](https://github.com/hackgvl/nights/assets/11095127/8a19c5db-47a0-4413-9167-7ce9c4b657d6)
Like this: 
![PXL_20240329_182931414](https://github.com/hackgvl/nights/assets/11095127/f14be573-e274-47fd-8443-cd96f457770c)
So the receipt is for 2 grand, but the whole bill for the boy that went into chili was about 15 bux, including dried peppers, shiner, etc.

I'll be there for the next one too.  Already submitted talk #2 from the You're Doing IaC Wrong series.

**Comment by TwonkyHardware** [comment]
I can't commit to cooking, at least not yet.  The only new food idea I can think of is something like a curry buffet, if we can find like a couple of giant rice cookers.  Then each chef can fix a curry (or anything that goes over rice, really) in a crockpot like we did with chili.  I also like the catered subs idea.

**Comment by allella** [comment]
I'm hip to the sub / sandwich idea.

After payment processor fees and incidentals, or budget on the higher side is $5 per person range, so turn-key catering for everything is likely going to be hard.  

I think we'll need to put our personal touch on it to keep within the budget. Plus, putting our spin on the food is something folks are coming to enjoy, as indicated by a number of people sharing that they enjoyed the food and our special touch.  

What if we combine some of the ideas mentioned and considering doing subs with a few options?
- cold cuts - chicken, turkey, or ham - I'm assuming we'd buy these at a deli. Any suggestions.  Or, I have a small meat slicer that might work with smaller stock. Though, I'm not sure this is practical besides perhaps 5 or 10 lbs
- chicken salad - make or buy? if buying where's a place with good, bulk that's reasonably priced
- tuna salad - I'd volunteer to make a batch of it
- egg salad - we could make or buy this
- cheeses
- toppings

For bread, one possible direction is using Swamp Rabbit Cafe's bread.  It's pretty great and they sell subs on the same bread.  Any thoughts on other breads?

I was out with friends on Friday and they rolled up with Swamp Rabbit Cafe subs for their kids.  I'm told the trick is to get / keep the bread fresh so it doesn't get too hard.

**Comment by TwonkyHardware** [comment]
I can make a good bunch of chicken salad.  2-3 lbs classic and 2-3 lbs curry wouldn't stretch me too much, especially since I could split the work over a couple of days.  I'd also definitely recommend the SRC's stecca if it's in the price range, that stuff's great.

**Comment by TwonkyHardware** [comment]
Also came across this egg salad recipe recently: https://cooking.nytimes.com/recipes/1024621-egg-salad.  Never made it, but it looks both good and easy.

**Comment by allella** [comment]
How about a Subs and Sliders concept?

Get some trays of subs from Publix as a base and do a few types of sliders?

My wife's family makes these ham sliders that are amazingly good and easy.
https://www.allrecipes.com/recipe/216756/baked-ham-and-cheese-party-sandwiches/

We could get some Swamp Rabbit bread and cut it into slices and put chicken salad, egg salad, or some vegan option (veggie spread or some such) on them.

**Comment by allella** [comment]
[SRC Stecca Bread](https://swamp-rabbit-cafe-catering.square.site/) is $3.75 per loaf or $3.50 per when ordering by the dozen, which I don't think we'd use that much on just sliders.

**Comment by TwonkyHardware** [comment]
Those ham sliders rock!  I've had those before.  For a vegan option, I've been meaning to try out a curry tofu banh mi the way the Swamp Rabbit Cafe does, so I might could give that a shot.  I don't think I could do that and chicken salad, though.  Especially if I end up doing talking

**Comment by allella** [comment]
Yeah, I'm good to make ham sliders and some other "salad", so pick whatever you like?

@sirbeep do you have any inspiration on bringing something into this combo of Publix subs as a base and us making smaller sliders or open-top bites on top of slices of Swamp Rabbit Cafe stecca?  We could also include some specialty toppings to go with the subs and/or smaller bites.

**Comment by sirbeep** [comment]
I've got topping.  I was planning to bring my award winning savory spread.  carmelized onion n stuff.  possibly 2 spreads, the savory and a fresh.

**Comment by TwonkyHardware** [comment]
Reddit thread to mine for ideas for the next go-round: https://old.reddit.com/r/Cooking/comments/1ck750h/what_to_serve_at_a_party_that_is_like_a_taco_bar/

**Comment by allella** [comment]
Here's what I'm thinking for the menu for next week

Ham Sliders and Mexican Bean Salad - Jim
Chicken Salad - Joel
Spreads - Brian - award winning savory and non-savory spreads - would these go directly on the stecca bread?
Publix Subs - Eric order and pickup - perhaps a couple options and a veggie option
Stecca Bread - Swamp Rabbit Cafe - Jim will order

The curry tofu banh mi sounds interesting, but I'm imagining some folks will see tofu and not know what to think.  Also, I'm imagining the Publix order could cover the veggie / vegan folks with an option.

Thoughts @TwonkyHardware @sirbeep @eric-hemasystems ?

**Comment by sirbeep** [comment]
"would these go directly on the stecca bread?"  
yup, mayo alternatives... or .. mayo extension since mayo is an ingredient of 'em.

Savory: strongly flavored.  Think Ploughmans Lunch in a spread.
Fresh: mild and light.  Think teatime cucumber sandwitches in a spread.

**Comment by allella** [comment]
Mexican Bean Salad eaten with tortilla chips or as a side. It's always been a crowd-pleaser

![image](https://github.com/hackgvl/nights/assets/1777776/8f53e396-c0e0-4972-aba6-1923afe31414)

**Comment by TwonkyHardware** [comment]
I tested out a new curry chicken salad recipe this week, it makes 2lb easy, adaptable to 4lb.  Would 2lb classic/2lb curry be enough, or should I bump one or both of those to 4lb?

**Comment by allella** [comment]
We're currently at 34 RSVP'ed. I suspect we'll end up in the 50-60 people range, but we'll have to keep an eye on it and we can either cap the RSVPs or bump up our quantities as we get closer.

I think if we do like we did last time, we can each try to provide enough to feed 1/4 of the people, so best guess right now is about 15 people per dish.

A can of tuna is about 4 oz, so I wouldn't imagine 3-4 oz of meat salad on bread would be plenty per person.  Therefore, 2 lbs of class and 2 lbs of curry is probably more than sufficient even if we go over 60 people.

Looking back at [the taco night, we used about 9 lbs of meat and beans to feed ~ 50 people](https://docs.google.com/document/d/1ZBEl61eH4kB6NVHqjrlEgnYyRrfONAyJoQXFcH5muaQ/edit#heading=h.66opqi4iu821), and that was with tortillas and light toppings instead of less filling bread.  So, rough guess is 2.5-3 ounces of protein per person would be a starting estimate for something on bread.

Thoughts on that?

**Comment by allella** [comment]
Also, the budget is the other constraint.  As a starting point, we can say $50 per volunteer, and if we need to spend more on things, then we can talk about it. The sponsorship was for $400, but we lose about 3 or 4% of that with fees and we'll be buying things like plates, drinks, bread, tortilla chips, and beer and snacks for volunteers, so spending $200-$250 on food in total is probably a fair overall budget.

**Comment by allella** [comment]
@eric-hemasystems what do you think about ordering these from Publix?

$39.99 (feeds 25) https://www.publix.com/pd/publix-deli-cubanitos-platter-large/RIO-PLT-120391?origin=collections12

Mix of veggies option and perhaps select one with no cheese
$24.99 (feeds 8) https://www.publix.com/pd/publix-deli-veggie-wrap-platter-small/RIO-PLT-120196?origin=collections23

**Comment by allella** [comment]
Also, I think we can skip the mayo and mustard packets.  If we think we need them I can bring or pick up some squeeze condiments.

**Comment by allella** [comment]
@eric-hemasystems @TwonkyHardware @sirbeep here's the updated menu with notes.  Please holler with any questions or adjustments.

Remember to save all receipts so RefactorGVL can reimburse us all.

### Menu
- [Publix Cubanitos (~ 25 people) and Veggie Wrap Platter (~ 8 people)](https://www.publix.com/mc/order-ahead/landing) - Eric
- [Ham Sliders](https://www.allrecipes.com/recipe/216756/baked-ham-and-cheese-party-sandwiches/) - Jim (~ 15 people)
- Swamp Rabbit Cafe Stecca Bread - Jim - probably about 8 loaves
- [Mexican Bean Dip](https://github.com/hackgvl/nights/issues/17#issuecomment-2102801492) and Tortilla Chips - Jim
- Chicken Salad and Curry Chicken Salad to top sliced stecca (JIM WILL GET THE STECCA) - Joel - 2 lbs of each
- Savory and non-Savory Spreads to top sliced stecca (JIM WILL GET THE STECCA) - Brian - enough to feed about 15 people

**Comment by sirbeep** [comment]
K!  I've got time to look and see what ya'll are talking about. 

Whas'a Stecca?  .. well, I know what's a stecca, in Italian that's a stick..   So guessing breadsticks?  

Spreads I meant like extended mayo for a sandwitch bar.  Thick condiments, not chicken salad.   Take some rye bread, spread some of the savory spread on, add roast beef and 'maters and you get a flavor explosion.  

Though.. now that I think about it, that's probably a GREAT use for it.  slather it thick on some foccacia and it's a meal.. 

Nevermind..  :smile:   I just change from British to Italian flavors.. throw out the Stilton for some Gorgonzola, etc..  
What's the breadsticks so I can match the flavors?  cheese covered, spices covered or dried 'mater covered like foccacia?

**Comment by allella** [comment]
@sirbeep The stecca at Swamp Rabbit Cafe is a semi-hard, long, thin loaf with some salt on top.

The plan for the chicken salads, and items was to cut and top it with things like heavy appetizers.

I think it would be good with about anything on top that goes well with breads.

I was imagining your spreads were heavy and could be used by themselves.  Though, if they are more of a condiment, then we'd obviously want to pair it was something.  

We're talking about having chicken, pork, and veggie options between Eric / Publix, Joel, and I.  If you're spreads go well with roast beef, or something else, then that sounds like a good complement if you're up for it, and that works within the roughly $50 budget we're starting with for each of us to aim to serve 15 people's worth of food.

I could see a tomato sandwich with a spread if we were in tomato season, but I doubt we'd get anything fresh enough this time of year to be good.

**Comment by allella** [comment]
https://swamp-rabbit-cafe-and-grocery.square.site/product/stecca-bread/13?cp=true&sa=false&sbp=true&q=false&category_id=83

**Comment by sirbeep** [comment]
yup.. they're not mayo thin,  they're heavy.  just not chicken salad heavy.   full of onion, cheese, etc..   Spread on sticks is actually a good idea, it just wasn't what I had in mind at the moment.   For Salty sticks I'll just add a bit of Italian spices to the savory and it'll be perfect..  I just need to think on the fresh one how to balance the salt.

**Comment by allella** [comment]
On Thursday, there will be traffic around The Well coming into town from I-385 and there will be a crane blocking part of the road between the two parking decks on Richardson St.  So, you may need to come into the Richardson St garage from the north.

![road-closure](https://github.com/hackgvl/nights/assets/1777776/895dcdd8-816d-43d1-af3a-46496d6ebcd9)

**Comment by allella** [comment]
@TwonkyHardware @sirbeep I'll print out the ingredients on signs we place next to the food if you'll share the ingredients of your custom creations.

@eric-hemasystems if you can send me the ingredients from the Publix order, then I can turn that into a sign too.

Thanks.

**Comment by TwonkyHardware** [comment]
The regular recipe I was going to wing a bit, but if you need to go ahead and print, print this whole list and I'll Sharpie out the ingredients I don't end up using.

Classic chicken salad:
* chicken
* mayonnaise
* Greek yogurt
* sour cream
* dijon mustard
* red grapes
* almonds
* lemon juice
* parsely
* red onion
* celery seed

Curry chicken salad:
* chicken
* onion
* mango chutney
* tomato
* lemon juice
* red wine
* curry powder
* mayonnaise
* apricot
* butter

**Comment by sirbeep** [comment]
Savory spread: 
Carmelized Onion,
Some Shrooms I found in the yard..  :) or whatever kind I find at the store, sometimes they have more flavorful varieties than plain button mushrooms, but sometimes not.
Gorgonzola cheese
Southern Mayo
turkish oregano buds
pepper(piper longum, even more aromatic than piper nigrum)
marjoram
thyme
All the Biggest Flavor versions of each ingredient.  Boom in yo mouth!

Fresh spread:
Cucumber
Mascarpone
green onion
Mayo
dill
Pepper

**Comment by allella** [comment]
Thanks. These all sound great.

**Comment by allella** [comment]
@eric-hemasystems I got the ingredients for the cubanitos off the Publix site.  If you can let me know which veggie sub option / ingredients when it's ordered, then that's all I'll need for a sign.

Thanks

**Comment by allella** [comment]
I'm making notes on how much we had left over for the sandwiches and sliders.

I didn't see what was left over.  Can anybody recall how much subs, bread, and such was left?

**Comment by TwonkyHardware** [comment]
Probably half the chicken salad I brought was leftover. I don't think much stecca was left, except what was under the chicken salad. The ham sliders were gone completely.
