### ISSUE TITLE
2024 Q2 Event - Speakers and Format

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#18]
## Confirmed Speakers

- 10 mins (or 15 if we'd like) | Andrew Thompson | How Not to Give a Talk | Do you enjoy the glazed look in people's eyes as they fully disengage from your presentation? Have you experienced the thrill of swimming in front of an audience with no direction or paddle? If so, then this might is the talk for you--gleened from years of one off mistakes and repeated failures by the presenter, you too can learn how to spike your very own talk in a few simple steps!
- 10 mins (or 15 if we'd like) | Joel G | Random Numbers from Cosmic Rays (Step 1) | The presentation will summarize the first stages of a hobby project to construct a hardware random number generator using small cosmic ray detectors.
- 15 mins | Pete Dunlap | Decentralized Community Building Via Twilio
- 15 mins |  James Shockley | Scratch, Dent, and Data: Engineering A Used Appliance Information Advantage Out Of Necessity | After moving to a new-to-us apartment and finding that the community coin laundry value proposition was in a flux state of being just too inconvenient, just too unreliable, and just too expensive, my partner and I opened the door to what we would find to be our biggest relationship hurdle so far- purchasing a value laundry set.After being beaten to the close on the first few deals we moved out to execute, it was clear we could not compete with the rest of the market's hustle and grit on a fair footing. The only way we could compete would be if we had an information advantage.This is the story of personal discovery in learning that, after practicing one kick 10,000 times, you might one day find a surprising number of situations that you can just kick your way out of.The last few minutes of this talk will be reserved as a museum for sharing all the interesting novelties and oddities I found while scraping and aggregating 70+ used appliance provider inventories throughout SC, NC, and GA.

## Schedule

6:00 - 6:20 — Food - Subs and Sliders Picnic
6:20 - 6:25 — Welcome and Intro to Sponsor Neurelo 
6:25 - 6:35 — Andrew Thompson on How Not to Give a Talk
6:35 - 6:40 — Break and Brief Community Announcements
6:40 - 6:55 — James Shockley on Scratch, Dent, and Data: Engineering A Used Appliance Information Advantage Out Of Necessity
6:55 - 7:10

- Break
- Community Breakout Conversation | UpWiSE Gathering in Room 1

7:10 - 7:20 — Joel Griffith on Random Numbers from Cosmic Rays (Step 1)
7:20 - 7:35 — Break
7:30 - 7:45 — Pete Dunlap | Decentralized Community Building Via Twilio
7:45 - 8:00+ — Social and Ice Cream Bars

### Potential Future Talks
- [Barry Jones](https://github.com/hackgvl/nights/issues/3#issuecomment-1922016402) - (As a backup) Lightning Talk | _Ruby ActionMailbox for Parsing Inbound Emails_
- Luke Kapustka (LukeTech on Slack) on Pros and Cons of 5G Home Internet Service - inspired by a [Feb 2024 Slack thread](https://hackgreenville.slack.com/archives/C0420TN6W/p1708459314090209?thread_ts=1708448544.205969&cid=C0420TN6W)
- Jeremy Wight - "Building a tech company with social impact? Why a Non Profit entity type could be your super power.”
- 
## Notes
- [2024 Q1 Speaker and Format notes](https://github.com/hackgvl/nights/issues/3)
- [The Oct 2023 pilot event speakers and topics are listed on the Meetup event.](https://www.meetup.com/hack-greenville/events/296051672/) 
- The [pilot notes contain potential speakers, and potential future speakers / ideas / topics](https://docs.google.com/document/d/106st3E4nNViZhedZ6N2ZJE9W0J_wvN0-0VmZjQftio0/edit#heading=h.5kzk7h2e7g65).
- We agreed to post a call for speakers and in #random on the Slack and Jim will reach out to people who expressed interest for the pilot event.

## Format
- Pam suggested "[at least one speaker before breaking out into other rooms](https://hackgreenville.slack.com/archives/C0JPADQDD/p1705509800769809?thread_ts=1705507321.527509&cid=C0JPADQDD)"
- Eric suggested we may have the [potential speakers help define the format / time slots](https://hackgreenville.slack.com/archives/C0JPADQDD/p1706284911339419?thread_ts=1705507321.527509&cid=C0JPADQDD).
- Jim suggested a balance would be [a single track speaker of perhaps 20-25 minutes max and the rest of the event as break outs / multi-track](https://hackgreenville.slack.com/archives/C0JPADQDD/p1705509800769809?thread_ts=1705507321.527509&cid=C0JPADQDD).

## Tasks (In-advance)
- [x] Reach out to speakers who have previously expressed interest and invite them to fill out the [Talk Submission form](https://forms.gle/gudqeQwpjQmR7QLV6).
- [x] Post a call for speaker / talk submissions in #community-organizers directing people to fill out the [Talk Submission form](https://forms.gle/gudqeQwpjQmR7QLV6)
- [x] If needed, post a call for speaker / talk submissions in #general or #random a week or so after posting in #community-organizers
- [x] Offer lightning talks to organizers of groups which are on hiatus or which have low attendance
- [x] If needed, ask community partners to promote the call for speakers to their relevant audience
- [ ] Have a backup speaker for when someone is sick or can’t make it.
- [x] Advise speakers to come with proper video adapters to connect their laptop via HDMI
- [ ] TODO Consider grading the talks on skill / knowledge level: newbie, intermediate, advanced and having a mix of different levels
- [x] (Jim has a template) Connect with speakers over Slack to share details (audio / video setup, share Wi-Fi details, time slots, attendee expectations (like expecting people to come and go during the talks), video recording, [where to park and how to enter the building](https://joinopenworks.com/guest-access)
- [x] Ask if speakers need any special equipment, like power cords, whiteboards & markers, podium, audio speakers, time clocks, projector
- [x] Suggest that speakers come early to test Wi-Fi, video, and other connections

## Tasks (At the Event Venue)
- [ ] Take a photo of the space before hand so things can be put back where they were
- [ ] Prepare the conference rooms (move the white tables to the empty hall past the men's room at OpenWorks)
- [ ] If opening the partition in the conference room
  - [ ] Get Jim Ciallella to help, or else contact the security desk for help, as the wall requires special know-how and has been damaged in the past by unskilled folks messing with it.
  - [ ] WARN people about putting their fingers in the seams
  - [ ] WARN people to move the TVs away from the wall before folding the wall
- [ ] Position and erase whiteboards
- [ ] Confirm audio / video / internet is working for the presenters
- [ ] Double-check that the presenters brought proper HDMI to Laptop adapters
- [ ] Turn on TVs and set to the correct “source”
- [ ] Remind speakers to test the HDMI and do a dry run to make sure they have what they need

**Comment by allella** [comment]
I've started reaching out to potential speakers and marking them as bold in the original HG Nights Pilot Google Doc where some older ideas have been saved.

**Comment by allella** [comment]
For this HG Nights, we have 4 submissions on the new form from folks who have never given a talk at the event + 3 from folks who gave a talk in Feb.

I figured we could prioritize newbies and volunteers.   Sirbeep and I are volunteers, but we also gave talks in Feb.

I reached out to Brian to gauge his level of caring about doing back-to-back vs pushing to a future event.  I'm not worried about me giving a talk unless we need filler.

Also, the [HG Committee minutes](https://docs.google.com/document/d/1kxeXaKxOnZBP1Ca9J03RjQTIrQ7KCL8T-gDBH0UhiMc/edit#heading=h.9hq50eu3vhdc) suggested more social time and perhaps 3-4 talks.   I'm figuring we can scale down to 4 or 5 talks to start and re-evaluate from that point instead of cutting the talks in half, since we have 7 people willing to share.

**Comment by allella** [comment]
4 out of 4 newcomers have confirmed, as noted the original issue post.

We have 3 other talks that were submitted, but each was from someone who spoke in February.

Given the Committee wanted to try "more social time", we'll try 4 talks and perhaps make them serial instead of breakout rooms.

**Comment by allella** [comment]
@sirbeep @peoplespete and I all spoke in February, and submitted more talks.

We're going to try a 4 speaker format and since we had 4 newcomers, we gave them first priority.

So, we're going to go with the list of first-time HG Nights speakers on this one.  If anybody wants to be a backup for this May event, then please holler.

**Comment by allella** [comment]
Thanks again for submitting and we'll keep everyone on the list for a future HG Nights.
