### ISSUE TITLE
2024 Q2 Event - Volunteers

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#19]
The [pilot event's notes have a volunteer section](https://docs.google.com/document/d/106st3E4nNViZhedZ6N2ZJE9W0J_wvN0-0VmZjQftio0/edit#heading=h.tervj73plqz) with past volunteers. Plus, it includes some people who weren't able to attend the pilot who offered to assist in the future.

### Volunteers
- Food Volunteers - [we have 4 commitments to help with the food](https://github.com/hackgvl/nights/issues/20) - Brian Kennedy (4:30 - 5:00 PM), Joel Griffith (5:00 PM), Eric Anderson (5:00 PM), Jim Ciallella (4:00 PM)
- Olivia - video
- Setup / Breakdown
  -  Zach Robichaud (5:40 PM)
  - Matt Irby (5:00 PM)
- Check-in and [Promo Whiteboard](https://github.com/hackgvl/nights/issues/26) - Jas (4:00 PM) 
 
### Tasks
- [x] Get commitments from volunteers for the upcoming event
- [x] Ask volunteers to RSVP to the event
- [x] Connect with volunteers and share necessary tasks / details with them
- [x] Confirm about with any video recording volunteers https://github.com/hackgvl/nights/issues/5
- [x] Communicate with volunteers about when they need to arrive, tasks, and such
- [x] Ask volunteers to raise their hand at the event if they see a speaker or other volunteers with a hand up. This worked well at the Feb 2024 event to interrupt the crowd without having to do so abruptly.
- [x] Communicate with volunteers about where to park to unload and how to get into the building if they arrive before the doorbell is up.

#### 2024 Q1
- Food Volunteers - [we have 4 commitments to help with the food](https://github.com/hackgvl/nights/issues/2) - Brian Kennedy, Joel Griffith, Eric Anderson, Jim Ciallella
- Bogdan Kharchenko - ~ 5 PM arrival - [as needed](https://github.com/hackgvl/nights/issues/6#issuecomment-1924042963)
- Jacob Adelberg - arriving around 5:30 - lobby door, setup and breakdown
- Zach Robichaud - offered to help with setup and breakdown - likely will arrive around 5 PM 
- Alan Johnson - event photography
- Jack Brackley - arriving around 5:00 - setup
- Video Recording - Olivia Sculley, Joey Loman, Matt Thornton

#### 2023 Q4
- Barry Jones - identifying speakers
- Eric Anderson - offered to help with whatever, helping with food prep @ 5PM
- Brian Kennedy - helping with day of food prep @ 5PM
- Alex Dresko - setup / breakdown and bot whispering
- Olivia Sculley - setup & breakdown, check-in, photos, planning
- Pamela Wood Browne - setup & breakdown, check-in, photos, planning
- Jim Ciallella - planning, setup / breakdown and project management
- Ryan Lanciaux - coordinated speakers in Michigan, but offered to help with whatever
- Alan Johnson
- Hunter Hodnett - previously mentioned interest in identifying sponsors
- Pete Broderick - set-up - 5:15 - 5:30
- Jacob Adelberg - lobby greeter, setup - 5:45
- Zach Robichaud - 5:15 - 5:30

### Offered to Volunteer in the Future

- Ryan MacAllan - (on hiatus) food procurement and/or sponsorship
- Steven Wade - speaker, eventually may be able to helping with some organizing
