### ISSUE TITLE
2024 Q1 Event - Food & Drink Planning

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#2]
### Food Volunteers
- sirbeep / Brian Kennedy
  - "the winning chili" [beef "Texas-style" base](https://github.com/hackgvl/nights/issues/2#issuecomment-1954351306), non-hot peppers -  3 quarts
  - 2 pans of the texmex cornbread / masa harina corn pudding
  - ladle for serving
  - hot sauce
  - slow cooker
  - 4:30 arrival
- eric-hemasystems / Eric Anderson
  - [beef and bean base](https://github.com/hackgvl/nights/issues/2#issuecomment-1954948517) - double batch, likely around 4 quarts
  - hot sauce
  - ladle for serving
  - slow cooker
   - 4:30 arrival
- TwonkyHardware / Joel Griffith
  - [turkey and bean base](https://github.com/hackgvl/nights/issues/2#issuecomment-1953412604) - 3 quarts
  - hot sauce
  - ladle for serving
  - slow cooker
  - 5:15 - 5:30 arrival
- allella / Jim Ciallella
  - [bean / vegan base](https://github.com/hackgvl/nights/issues/2#issuecomment-1953378796) - double batch, likely around 4 quarts
  - slow cooker, cutting boards, knives
  - toppings to be prepped on site: cheddar cheese, onion, hot peppers, crackers, scallions, sour cream, tortilla chip, cilantro
  - ladle for serving
  - serving bowls and utensils for the toppings
  - bowls, spoons, napkins
  - drinks
  - 4:00 arrival

### Hot Plates / Slow Cookers
If we need these to keep things warm, then people offered.
- sirbeep - dual hot plate
- @ThorntonMatthewD - has a couple of slow cookers and a hot plate

### Budget

- We agreed to provide a set amount per batch, and assuming it will feed a specific number of people
- It sounds like most recipes are for 6-8 servings, but will likely feed more like 10-12 people in this casual setting.
- [Jim suggested catering and recipes can typically be cut by 25-40%](https://hackgreenville.slack.com/archives/C0JPADQDD/p1706472825699389?thread_ts=1706289280.129669&cid=C0JPADQDD)
- The [SnackGreenville document](https://docs.google.com/document/d/1ZBEl61eH4kB6NVHqjrlEgnYyRrfONAyJoQXFcH5muaQ/edit#heading=h.374owrq3m4r2) has recent history, including the prices and amounts used for the HG Nights pilot taco bar.
- $20 to $25 per 10 person batch is what sounds reasonable
- Best guess at this point is we'll have 40-60 people register for the event
- Volunteers will likely be reimbursed through _[Expensify](https://www.expensify.com/)_. We might expect this to be paid before the event, as long as the sponsor funds are deposited well enough in advance to make it happen.

### Other Food and Desserts
- Corn bread was mentioned
- Toppings
  - cheese, scallions / green onions, onion, sour cream
  - this would likely be a combination of offsite and onsite prep
- We did an easy and cheap dessert handout about 15-20 minutes before the wrap-up event with ice cream sandwiches and thanked the physical location host (OpenWorks) for hosting. People seemed to enjoy it, though some people had already left, so we didn't need 1 per person
- Beer - For the pilot this was a perk for volunteers.  Given the liability and added cost, this could remain a volunteer-only perk

### Drinks
- Canned drinks seem to work best and can be recycled at OpenWorks
- Sparkling Water - We have 3 12 packs of sparkling water left over from the pilot. These are in the kegerator refrigerator at OpenWorks, but that isn't cooling, so we'd need to transfer them to a refrigerator well in advance, or else ice them
- Soda - We have 1 leftover 2 liter of "Starry" (Sprite equivalent) and 1 12 pack of ginger ale, it's also in the kegerator refrigerator at OpenWorks
- There are about 30 16 oz bottles of water in the kegerator refrigerator at OpenWorks

### Tasks (In-advance)
- [x] Put out a call for volunteers (as w/ (https://hackgreenville.slack.com/archives/C0JPADQDD/p1706289280129669))
- [x] Dietary or allergy considerations - check to registration form responses
- [ ] Instruct volunteers to save any receipts for reimbursement
- [x] Gather recipe ingredients so they can be printed on signs for allergy considerations
- [x] Pay for any prepared food from vendors, either in advance, or at pickup. 
- [x] Check the vendor's hours of operation and pick-up details in advance
- [x] Communicate with volunteers
- [x] Designate a reliable pick-up person and share the pick-up time and details of how to unload the food at the venue
- [x] Determine if drinks can be refrigerated in advance, or if ice and ice bins are needed. - Jim has some 6" tall plastic totes which we've used in the past to ice drinks, and they could be used upon request.
- [x] Determine if any prepared food needs to be refrigerated and confirm there is space - OpenWorks has a large and small refrigerator and there is typically space as long as the refrigerators have been cleaned out of old stuff
- [x] Determine if a freezer is needed and available at the venue. - OpenWorks has a very small freezer, so we'd definitely need to verify space in advance.
- [x] Purchase any food, drinks, plates, napkins, etc in advance
- [x] Purchase volunteer beer and any special volunteer snacks.  A 15 mix pack of Oskar Blues beer is usually enough. 
- [x] Reimburse any volunteers for budgeted food costs

### Tasks (At the Event Venue)
- [ ] Prepare any food that’s being made on-site
- [ ] Setup food, serving bowls, serving utensils (spoons, tongs). Setup TWO serving utensils for EACH of the main dishes so people can serve from both sides of the bar.
- [ ] Setup bowls / plates at check-in table so people need to check-in before they can eat.
- [ ] Setup napkins, forks / spoons at the end of the food line / upper bar, so people don't have to hold these things while they are making a plate
- [ ] Put forks or spoons in a container, like a mason jar, or small bowl, with the handles facing up / out so people can grab them by the handle.
- [ ] Avoid putting any very hot items directly on the wood counter tops. Use a trivet or other something under hot items. 
- [ ] Move the trash and recycling cans out of the way, but still in a visible spot.
- [ ] Setup a bus bucket near the trash cans for dirty utensils / dishes
- [ ] Setup any food heating (ovens, crockpots, hot plates, microwave) or chilling equipment using heavy power cords if needed and try to not put everything on the same circuit, if / when it's possible to tell.
- [ ] Setup drinks, ice, cups on a rolling table at the very end of the food line, or even near the check-in, so people aren't trying to hold a drink while they are making a plate. We'll likely roll this drink table out of the kitchen and into OpenWorks' Social Lounge for the later half of the event.
  - Cans
    1. [ ] Setup cans - Ideally, keep cans in the cardboard boxes and open 1/2 of one end of the box and put something under the rear of the box so the cans roll forward to the opening for easy grabbing.
    1. [ ] Otherwise, if cans are not cold then it may not be necessary to ice them down in a bin.
    - Note: If icing down the cans, put cans into any bins before pouring the ice on top. Otherwise, it’s very hard to put the cans into shallow ice.
    - Note: Icing cans will often cause condensation, so putting a towel or thick piece of cardboard under the cold bin can help insulate the bottom and limit a wet mess
  - [ ] If using 2-liters, then setup the bottles and cups - (Note: OpenWorks has a bunch of small foam cups in the lower cabinets opposite the bar stools)
  - [ ] (Optionally) Setup clean ice bucket w/ drinking ice & tongs - ideally this isn't needed when serving refrigerated cans
- [ ] When the line forms, encourage people to use both sides of the bar to double the throughput of the main course.

**Comment by allella** [comment]
@TwonkyHardware @sirbeep @eric-hemasystems 

We're 10 days from the HG Nights and I hoped to get us all to reply to the questions below, and read and share notes with each other in preparation.

## Questions
- **Are you bringing a slow cooker, a pot, or both?** Slow cookers may be the easiest to transport and to keep warm.
  - If you're planning on doing pots, then we need to coordinate on the hotplates (Brian offered one). 
  - Note that a double batch will pretty much fill my slow cooker, so keep that in mind when planning.
- **What time would you expect to arrive?** The event starts at 6 PM. For the pilot, people arrived early and the food wasn't fully laid out.  So, we should plan for being ready by 5:45-5:50.
- **Does anybody have anything that needs to be refrigerated?**
- **Does anybody want to help prep toppings on site?** We had a good time prepping things at the last event. Unless folks want to prep toppings in advance, and bring, them, then I can  buy the toppings and can do the prep work on-site. 
- **How many servings do you anticipate bringing?** Keep in mind that people will be standing and eating for perhaps 15 minutes and they will almost certainly not eat a sit-down portion.
- **Does anybody plan to bring any other small sides, like a cornbread**?
- **@sirbeep are you still planning on bringing masa harina corn pudding**?
- We should probably avoid making these dishes any hotter than a typically person might like. So, **would we want to bring or buy any hot sauces or hot spices** for those who want to kick their bowl up a notch 
- **Thoughts on toppings?**
  - We've mentioned cheese. **Any preferences?**
  - Other suggestions: scallions / green onions, raw onion, sour cream, cilantro?
  - **Anything else, or any veto votes of this list?**
- Any other questions or thoughts?

## Actions Needed
- For the pilot, we printed signs with who prepared the dish and the ingredients. Unless someone has a secret ingredient, we could list the ingredients on the sign too.  So, **please share your ingredient list**.
- Please plan to **bring a ladle, or other serving spoons** for your dish(es).

## Notes
  - We have [44 people registered for the event](https://www.meetup.com/hack-greenville/events/299063777/). Best guess is we'll end up around 60. 
  -  The initial though was for each of us to cover 15-20 people, which would mean enough for 60 to 80 guests.
  - I doubt we'll get to 70 or 80 people and we can always cut of the registration at some point if needed.
  - Many recipes seem to over-estimate 
- We initially agreed that $40 - $50 for each of us should cover costs.  $50 would be the max reimbursement since HG is limited to spending no more than the event sponsorship money. This is the first time we've had a "bank account" (via RefactorGVL), so there's no buffer in the bank, which we hope to have for future events.
- RefactorGVL is likely going to use Expensify to reimburse folks, which I'm told is easy and has no fees.
- Since we may not be purchasing ingredients until the week of the event, I'm wondering if we're all fine waiting to be reimbursed right after the event. 
- We have some large bowls and small tongs and some smaller serving spoons, but these will likely be used for the toppings
- We have vegetarian and dairy food considerations, but I'll have a vegan / dairy free option.

CC: @pamelawoodbrowne

**Comment by allella** [comment]
My answers

-I'm bringing 1 slow cooker
-I'll probably be there before just about anybody, so probably between 4 and 4:30
- We may have some small ice cream sandwiches again if people like that idea. If so, we can use the tiny freezer inside OpenWorks for those.
- I'll plan to bring some cutting boards and knives if we want to prep a few toppings on-site.
- I anticipate enough for 15-20 people
- I'm not planning to make anything besides the chili, but am open to suggestions.
- I'm going to cut the cayenne in half just to keep it a little less hot, and since people who are picky may gravitate to the vegan dish. 
- I'd vote for cheddar cheese, green onions, and cilantro on the toppings.
- My ingredients for a vegan Indian-style chili
  - Beans: Black beans, kidney beans, pinto beans
  - Veggies: onion, carrots, bell peppers, corn
  - Base: vegetable broth, tomatoes, olive oil
  - Spices: garlic, garam masala, turmeric, salt, cumin, paprika, coriander, curry powder, ginger
  - Heat: black pepper, cayenne, chili powder

**Comment by TwonkyHardware** [comment]
* I'll bring one slow cooker with a standard batch
* I can be there after 5.  I'll plan for 5:15-5:30.
* I have nothing that needs to be refrigerated, and I enthusiastically endorse ice cream sandwiches.
* I'll bring a cutting board and knife to prep some white onion and chili pepper topping.  Happy to help with other stuff.
* A standard batch of my recipe is ~6 dinner servings, or maybe 10-12 standing servings (more precisely, about 3kg/105oz/6.5lb)
* I won't have any other sides.
* I like hot sauce, but I don't usually put it in my chili.  I can bring an already-open bottle if there's demand, and also I'll have diced chili pepper as a topping.
* Toppings: I'll bring a white onion, chili pepper (jalepeno or serrano, probably), cheese (cheddar or a mix), and wheat saltine crackers.
* Ingredients:
   * ground turkey
   * black beans and dark red kidney beans
   * beef broth, tomato sauce and paste
   * garlic, chili powder, cumin, salt, onion powder, oregano, sugar, bay leaf, lime
   * heat: chili powder, paprika, cayenne, black pepper (mild overall)
* $40 will more than cover my expected costs
* I don't care deeply about how or if reimbursement happens

**Comment by sirbeep** [comment]
- bringing slow cooker full of the winning chili.
  - and you wanted me to bring my double burner hotplate I think.
- I'll be there 4:30
- nothing to refrigerate
- knife?  I'll have to make a list of stuff to bring. I might forget
- Whatever is a standard batch. I never counted. :) 2.5lbs of beef.  it'll pretty much be the same size as everybody elses
- 2 pans of the texmex cornbread, so double "usual servings"
- I'll bring hot sauces.  the chilis I use are mild, so my texmex rooted chili isn't texmex hot.  but it is chili
- ingredients:
  - beef chunks
  - guajillo, japones, *hatch*! chilies 
  - cumin, salt, pepper, masa
  - onion, garlic
  - no serranos and jalapenos, so safe for tongues.

**Comment by TwonkyHardware** [comment]
Wal-Mart had a bin of sample-sized hot sauces for $1 each today, so I grabbed 4.  That should be plenty when added to what sirbeep brings

**Comment by sirbeep** [comment]
I see nothing from the king of peppers,  Puckerbutt.   I'll bring a puckerbutt habanero and a pain is good jalapeno.  the jalapeno is the best addition to the winning chili.

**Comment by allella** [comment]
Just so we can size things appropriately, for my test batch a 1/2 cup soup ladle weighs about 6.5 ounces in finished chili.

I ate 1-1/2 ladles for lunch and it was filling.  Some bigger eaters may do 2 ladles or more, but my guess is 1-1/2 ladles is a good average. So, we might expect an average of 8 and 10 ounces of chili per person.

My test batch was about 2 quarts and I figure it's good for 10 people, maybe 12 servings when you add in that people will be eating toppings and corn bread and crackers and such.

So, it seems 5-6 servings per quart of finished product could be a reasonable number upon which to estimate.

**Comment by sirbeep** [comment]
actually.. mine's knda big.  it makes 3 quarts, not just 2.  2.5lb of meat chunks instead of usual 1.5lb ground.

**Comment by allella** [comment]
It would probably be easier if we all increase our recipes accordingly to cover 15-20 people.  So, perhaps increase by 1/3, or whatever ration needed to cover 1/4 of the attendance.  We will probably come in around 60 people and we can cap the RSVPs at 70 or 80 if we think it's going to stretch the food servings.

I'm going to do a double batch with the idea of covering about 20 servings.

**Comment by allella** [comment]
We can keep an eye on attendance. 

Eric and I likely going to bring 4+ quarts. Brian and Joel said they are about 3 quarts, so that should cover 70-80 people if my math / questimates are accurate.

**Comment by allella** [comment]
Sounds like we're covered on hot sauce, so thanks for everyone bringing what they mentioned.

On the toppings, Joel mentioned bringing a white onion, chili pepper (jalepeno or serrano, probably), cheese (cheddar or a mix), and wheat saltine crackers.

For more all-purpose things, like cheddar cheese, onion, hot peppers, crackers, scallions, sour cream, tortilla chip (?) I could pick those up and we can prep and put things into serving bowls.

@TwonkyHardware is that good with you or is there any special preparation or personal touch that you'd plan to apply?

**Comment by TwonkyHardware** [comment]
@allella Nothing special, what you've suggested sounds great!

**Comment by TwonkyHardware** [comment]
@allella I can bump it up by 1/3 and still be under $40.  I'll plan to do that.

**Comment by TwonkyHardware** [comment]
I have a couple of serving spoons I'll bring, plus the ladle.

**Comment by allella** [comment]
Yes, I have the toppings and they are already in the big refrigerator at OpenWorks.

Bowls, utensils, drinks, frozen treats and such are covered and already at OW or I'll bring them around 4 PM.

The issue at the top should be accurate as to what everyone else needs to bring and the tasks you'll be the primary on for tomorrow.

**Comment by allella** [comment]
I think we're good with the quantities of food everyone previously committed to, which was Eric and Jim doing double batches of about 4 quarts each, and Joel and Brian doing about 3 quarts + roughly 1/3 scale up they agreed to in the comments.

I figure that will probably be around 4 gallons of food, not counting the toppings and corn bread.

We had about 2 gallons of main course food at the pilot that fed about 55 people, so if that's any indication, then people should at least be able to get a first serving and I wouldn't be surprised if we had extra of some things.

**Comment by allella** [comment]
Yup, just put mine in the crockpot and nearly to the brim on an 6 quart crock.

**Comment by allella** [comment]
@TwonkyHardware @sirbeep how are things looking on your end?

Any last minute things I need to pick up?

I'm bringing:

- signage
- serving bowls and tongs for toppings
- two cutting boards
- full block of knives and sheers
- foil
- to-go containers
- a printed task list from this issue
- bowls, napkins, spoons
- extension cords
- beverage ice
- bin for loose drinks, like bottled water

**Comment by sirbeep** [comment]
I've got stuff.   2.5 pans of cornbread,  big oval cooker full of chili, knife, scooper, tongs, hotsauces, hot plate, etc..
I'll bug @Jas as ordered to get let in around 230-3 so I can plug up and I still need to fork shred any chunks.

**Comment by TwonkyHardware** [comment]
Looking good.  I'm bringing:

* 1 knife
* 1 cutting board
* 1 ladle
* 2 serving spoons
* 2 small tongs
* to-go containers
* 1 bag shredded cheese (Sargento's Cheddar)
* 1 white onion
* 2 long hot peppers
* 1 jalepeno pepper
* 1 red chili pepper
* 2 sleeves wheat saltine crackers
* 4 sample-sized hot sauces

**Comment by allella** [comment]
@TwonkyHardware I took care of [buying the sides for everyone](https://github.com/hackgvl/nights/issues/2#issuecomment-1957847764). Sorry, I thought your "[sounds good](https://github.com/hackgvl/nights/issues/2#issuecomment-1958545741)" was an acknowledgement.

If you've already bought stuff, then feel free to what you have and combine. If you haven't bought things, then the cheese, saltines, and onion are things included in what I bought.  In total for the toppings / sides, I'm bringing cheddar cheese, onion, jalepenos, crackers, scallions, sour cream, tortilla chip.

**Comment by allella** [comment]
I should add, to please bring the other things I didn't list.  So, you all can bring hot sauces, serving spoons, and any specialty items you want to bring.

**Comment by allella** [comment]
Thanks again @TwonkyHardware @eric-hemasystems @sirbeep (and me) for making the food.

@raiderrobert do you have a process for how we should go about submitting reimbursement on the food?  We budgeted up to $50 per person for the main dishes, but I think we all mostly spent less than that.

Also, I covered the drinks, toppings, and other misc needs, so I'll have a separate one for that that was probably about $60-70, so we should come out with a bit of money left in the HG Nights fund.

**Comment by raiderrobert** [comment]
@allella yup, we have an Expensify account. I need receipts to keep the IRS happy.

I'd like to start by doing just 1 person getting invited and reimbursed by to walk that person through it. So who would like to go first?

**Comment by allella** [comment]
I can go last since I likely have the most receipts.

@TwonkyHardware you want to lead us off on the Expensify run-through with Robert?

**Comment by raiderrobert** [comment]
Btw, I need an email address to invite!

**Comment by allella** [comment]
This repo is now public, so probably good we all Slack DM Robert an email address.

**Comment by TwonkyHardware** [comment]
I'll forgo reimbursement.  We'll call it a donation.
