### ISSUE TITLE
2024 Q3 Event - Food & Drink Planning

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#29]
See our earlier [Food & Drink Planning](https://github.com/hackgvl/nights/issues?q=food+planning+in%3Atitle+is%3Aissue) issues for past notes and context.

### Notes
- The [SnackGreenville document](https://docs.google.com/document/d/1ZBEl61eH4kB6NVHqjrlEgnYyRrfONAyJoQXFcH5muaQ/edit#heading=h.374owrq3m4r2) has recent history, including the prices and amounts used for the HG Nights pilot taco bar.
- At a past event we had 5 out of 75 attendees indicate a dietary allergy / constraint, including: peanut, pecan, dairy, vegan, and vegetarian concerns. This confirms we should avoid some ingredients, or else have at least one option which will satisfy these types of concerns.

### Menu

- Maque Choux with Chicken by @sirbeep 
- Potato Bar with Toppings by @eric1234 and @alexdresko 
    - Bacon bits
    - Chili
    - Butter
    - Sour Creme
    - Cheese
    - Jalapenos
    - Chives
    - Hot Sauce
    - Salsa
- Pork Sausage, Bell Peppers, Onions, Roasted Potatoes by @allella 
 

### <span id="ideas">Ideas</span>
- Taco Bar
- Chili Bar
- Sandwich & Sliders Bar
- Potato Bar
- Soup Bar
- See [Joel's link to a Reddit Thread](https://github.com/hackgvl/nights/issues/17#issuecomment-2098306696)

### Food Volunteers
- sirbeep - Brian Kennedy
- eric-hemasystems - Eric Anderson
- allella - Jim Ciallella
- TwonkyHardware - Joel Griffith
- Sally Anderson
- Austin Moede

### Hot Plates,  Slow Cookers, Griddle
If we need these to keep things warm, then people offered.
- @allella - 21" x 11" griddle
- @allella - convection oven
- @sirbeep - dual hot plate
- @ThorntonMatthewD - has a couple of slow cookers and a hot plate

### Budget
- Volunteers making food will have a set amount per batch based on the assumed number of guests they will be feeding
- Catering and recipes can typically be cut by 25-40%, as noted in the _SnackGreenville_ document (link above)
- Earlier events have range from 55 to 75 people and not everyone will eat
- Volunteers will be reimbursed through _[Expensify](https://www.expensify.com/)_. Reimbursement is usually handled after the event.

### Other Food and Desserts
- Toppings
- We have previously done an ice cream sandwich handout about 15-20 minutes before the wrap-up, which requires a freezer at the host location, and about half of the remaining guests tend to partake.
- Beer - Given the liability and added cost, this could remain a volunteer-only perk

### Drinks
- Canned drinks seem to work best and can be recycled at OpenWorks
- Refrigerating the drinks in advance and setting them out in the retail boxes on top of something to absorb condensation seems to work well
- Sparkling Water
- Soda
- Bottled water - we typically provide cups and ice if there's tap water nearby, as there is at OpenWorks

### Tasks (In-advance)
- [x] Put out a call for volunteers
- [x] Dietary or allergy considerations - check to registration form responses
- [x] Instruct volunteers to save any receipts for reimbursement
- [x] Gather recipe ingredients so they can be printed on signs for allergy considerations
- [x] Pay for any prepared food from vendors, either in advance, or at pickup. 
- [x] Check the vendor's hours of operation and pick-up details in advance
- [x] Communicate with volunteers
- [x] Designate a reliable pick-up person and share the pick-up time and details of how to unload the food at the venue
- [x] Determine if drinks can be refrigerated in advance, or if ice and ice bins are needed. - Jim has some 6" tall plastic totes which we've used in the past to ice drinks, and they could be used upon request.
- [x] Determine if any prepared food needs to be refrigerated and confirm there is space - OpenWorks has a large and small refrigerator and there is typically space as long as the refrigerators have been cleaned out of old stuff
- [x] Determine if a freezer is needed and available at the venue. - OpenWorks has a very small freezer, so we'd definitely need to verify space in advance.
- [x] Purchase any food, drinks, plates, napkins, etc in advance
- [x] Purchase volunteer beer and any special volunteer snacks.  A 15 mix pack of Oskar Blues beer is usually enough. 
- [x] Reimburse any volunteers for budgeted food costs

### Tasks (At the Event Venue)
- [x] Prepare any food that’s being made on-site
- [x] Setup food, serving bowls, serving utensils (spoons, tongs). Setup TWO serving utensils for EACH of the main dishes so people can serve from both sides of the bar.
- [x] Setup bowls / plates at check-in table so people need to check-in before they can eat.
- [x] Setup napkins, forks / spoons at the end of the food line / upper bar, so people don't have to hold these things while they are making a plate
- [x] Put forks or spoons in a container, like a mason jar, or small bowl, with the handles facing up / out so people can grab them by the handle.
- [x] Avoid putting any very hot items directly on the wood counter tops. Use a trivet or other something under hot items. 
- [x] Move the trash and recycling cans out of the way, but still in a visible spot.
- [x] Setup a bus bucket near the trash cans for dirty utensils / dishes
- [x] Setup any food heating (ovens, crockpots, hot plates, microwave) or chilling equipment using heavy power cords if needed and try to not put everything on the same circuit, if / when it's possible to tell.
- [x] Setup drinks, ice, cups on a rolling table at the very end of the food line, or even near the check-in, so people aren't trying to hold a drink while they are making a plate. We'll likely roll this drink table out of the kitchen and into OpenWorks' Social Lounge for the later half of the event.
  - Cans
    1. [x] Setup cans - Ideally, keep cans in the cardboard boxes and open 1/2 of one end of the box and put something under the rear of the box so the cans roll forward to the opening for easy grabbing.
    1. [x] Otherwise, if cans are not cold then it may not be necessary to ice them down in a bin.
    - Note: If icing down the cans, put cans into any bins before pouring the ice on top. Otherwise, it’s very hard to put the cans into shallow ice.
    - Note: Icing cans will often cause condensation, so putting a towel or thick piece of cardboard under the cold bin can help insulate the bottom and limit a wet mess
  - [x] If using 2-liters, then setup the bottles and cups - (Note: OpenWorks has a bunch of small foam cups in the lower cabinets opposite the bar stools)
  - [x] (Optionally) Setup clean ice bucket w/ drinking ice & tongs - ideally this isn't needed when serving refrigerated cans
- [x] When the line forms, encourage people to use both sides of the bar to double the throughput of the main course.

**Comment by allella** [comment]
Reposting from the [volunteers thread](https://github.com/hackgvl/nights/issues/31).

We could have a baked potatoes option, but I was thinking making 50+ baked potatoes would be hard because of the logistics of cooking that many and keeping them warm.

Rather, it could be a diverse range of potato dishes from casseroles to salads to soups, etc.
We could do "Starch" and call it "Starch Trek"

**Comment by alexdresko** [comment]
@allella What is involved with helping here? I noticed you were looking for one more person and I might be able to  help.

**Comment by allella** [comment]
@alexdresko We typically have 4 folks make and bring a dish of their choice that will feed about 1/4 of the expected attendance.

Often this is slow cooker dishes, casseroles, or similar dishes that can be made offsite and kept warm, or reheated at the event.

We also will prepare / chop / shred some of the toppings and such in the hour or so before the event starts.

The dishes are typically a personal favorite that people already know how to make, but it can be anything that fits the theme,  budget, and crowd's palate.

The budget has usually been about $50 per chef and actual expenses are reimbursed by RefactorGVL based on scanning receipts and posting them to an Expensify account.

The theme for this event is starchy and we'll probably do different things like a potato bar, potato soup, potato salad, or whatever else strikes the person making it.

Do you have a dish in mind?

**Comment by alexdresko** [comment]
I don't has a dish in mind because we don't typically cook. Maybe I'm not a good fit. :)  I'm more of a "tell me what to do and I'll do it" kind of guy. :)




Alex Dresko

See more at www.alexdresko.com<http://www.alexdresko.com>

________________________________

**Comment by allella** [comment]
@alexdresko if Eric is going to do a potato bar, then he could probably use a hand with baking and/or prepping toppings.

I'd suggested above that we could cut potatoes in half so people don't feel obligated to eat an entire potato, and so we can have room for other dish options.

We currently have 42 registered and that will likely get around 60, so we could cook like 25 or 30 potatoes and have enough for everyone to have a 1/2 with all their desired toppings, plus the other dishes.

**Comment by allella** [comment]
I'm thinking about making sausage, peppers, onions, and roasted potatoes  and having a smaller portion without the sausage for vegetarian / vegan folks.

@sirbeep do you have a dish in mind given my suggestion and that Eric and Alex are going to to do half potatoes in a bar / toppings format?

**Comment by sirbeep** [comment]
still a fan of Maque Choux.   it makes a good tater topper and side dish.  and I could add chicken or andouille if we need more protein.

**Comment by allella** [comment]
@sirbeep that sounds good.

If you want to do chicken in your dish, then I'll do a pork sausage in mine.

**Comment by alexdresko** [comment]
> To split up the work, I could bake the potatoes and @alexdresko could buy and prep the toppings?

My middle name is actually buy and prep the toppings, not DaSwagga.

**Comment by alexdresko** [comment]
The only question I have at the moment is whether I should heat the chili at home first or at the event. Oh, and are there serving dishes at OW, or should I bring my own ---fancy--- tupperware plating?

**Comment by allella** [comment]
@alexdresko we have a microwave if needed for reheating.

We have 5 small tongs for toppings, plus other crappier plastic tongs, and a bunch of serving spoons.

There are a few random small to large bowls and serving trays at OpenWorks, but the volunteers typically bring something to serve out of.  I'll plan to bring consistent looking bowls for the toppings, but we plan to serve out of whatever you bring things in as a backup in case I forget or don't have enough for everything.

**Comment by allella** [comment]
@sirbeep @eric1234 @alexdresko a few notes and questions are posted below.

**Head Count, Budget, Receipts**
- We're up to 56 [registered](https://www.meetup.com/hack-greenville/events/303551633/).  I'm imagining we'll hit around 60-65, but we'll keep an eye on the head count. At the last event it seems about 15% of people didn't eat.  At an earlier event that may have been around 20-25%.  Though, I suspect 15% may end up being more normal for a dinner.
- Right now we'd be looking at making enough for about 20 people per dish.
you have the ingredients, then please post them so I can get a jump on the signage.
- The typical budget has been $50 per dish for 4 dishes, but since we have 3 dishes we can say $65 per dish.  I'm imagining that should be more than enough, but holler at me otherwise.
- **Please save your receipts as they will need to be uploaded to Expensify for reimbursement by RefactorGVL.**
- The menu has been added to the event listing

**Jim Will Bring**
- I have some Tabasco-like Louisiana hot sauce from the OpenWorks lunch in Aug. @alexdresko I can bring that so you guys don't need to buy hot sauce if you're fine with it.
- I'll take care of the drinks, plates, napkins, tongs, forks, spoons, signage, and serving spoons.  I'll also plan to bring a few knives and cutting board. 
- I'll bring serving bowls for the toppings

**Needing Your Input**
- We'll display the ingredients for anything that's not obvious, which may only be the dishes from @sirbeep and me.
- @sirbeep can you shoot me your full ingredients list?
- I can bring a convection oven, but do we need it?
- Anything else we / I need to bring?
- Any questions or suggestions?

**Comment by allella** [comment]
@eric1234 I will have the convection oven and a griddle.

I could probably put my dishes on the griddle on real low to keep those warm if you wanted to come earlier and keep the potatoes in the oven.

**Comment by alexdresko** [comment]
I got nervous on the way to the grocery store tonight when it occurred to me that some things might be challenging to find due to the hurricane. 

All good on that front. Next fear is that I didn't buy enough. I made the best use of the funds without resorting to buying the absolute cheapest/fakest stuff available. I ain't about that life.  If we feel we need more of anything when I get there, I can run to Publix or HT. 

I like my potato toppings with a side of potato, so I'll have to let everyone else go first. :) I'm pretty sure I could use all of this butter, sour cream, bacon bits, and cheese on one potato all by myself.

**Comment by sirbeep** [comment]
MAQUECHOUX

 * 1 dozen ears fresh sweet corn
 * 8 tablespoons (1 stick) unsalted butter
 * 1-1/2 cups onions, finely chopped
 * 1 large green bell pepper, finely chopped
 * 1 large red bell pepper, finely chopped
 * 3 ribs celery, finely chopped
 * 3 large ripe tomatoes, peeled, seeded and roughly chopped
 * 2 teaspoons salt
 * 1 teaspoon cayenne pepper
 * 2 teaspoons freshly ground black pepper
 * 4 tablespoons sugar
 * 1 cup evaporated milk 

Shuck the corn and remove all of the cornsilk. Hold each cob over a bowl and cut the kernels away in layers 
(don't cut whole kernels), then scrape the knife along the cob to get all of the "milk" out of it.

Melt the butter in a large saucepan or pot over medium-high heat. Add the onions, bell peppers, celery and tomatoes
and saute until the onions are transparent, about 10 minutes. Stir in the salt and peppers, then add the corn and milk 
from the cobs, the sugar and evaporated milk and stir well. Reduce heat to medium and cook until the corn is tender, 
about 10-15 more minutes.


Plus chicken breasts in the butter to brown up before the onions.

**Comment by allella** [comment]
We're up to 65 people registered.  Best guess is something like 5 more people will RSVP, 20 people will cancel tomorrow or not show up, and about 10 people will walk in without registering.  So, net there will likely be around 60 people and perhaps 15%-25% of them won't eat, so we'll end up feeding about 50-55 people.

If we all bring enough to feed 20 people, then we should be good.

**Comment by allella** [comment]
@eric1234 @alexdresko @sirbeep 

Thanks again for everyone's hustle on the food. 

@raiderrobert I think everyone is in Expensify besides Alex Dresko, so please add him and I'm assuming the rest of us can log in and upload receipts, or do you need to create a specific thing in Expensify for each event?

**Comment by allella** [comment]
There was a salt shaker (glass with chrome top) left behind.  Was that someone's, or was it just one that was already in the kitchen?

**Comment by allella** [comment]
@raiderrobert I submitted to Expensify.  The workspace said (archived), but I used the Refactor email and it allowed me to add new expenses to _RefactorGVL Admin_.

For @alexdresko @sirbeep @eric1234  The email address is [admin@refactorgvl.com](mailto:admin@refactorgvl.com)  and then you should be taken to a RefactorGVL "workspace" which looks more like a chat window and then you can click the + sign in the right / chat side and Submit Expenses.  Then, upload each receipt / vendor one at a time and it will try to OCR the vendor and amount and you can verify and submit for reimbursement.

Somewhere in there you'll need to add a bank account, but I think that's part of the joining process.

**Comment by alexdresko** [comment]
@allella Sorry, instructions not clear. Where do we go to enter that email address?

**Comment by allella** [comment]
@alexdresko it's a testament to Expensify's UI being too cute that I had to explain those steps, and that I forgot to mention the main trick before it is that  you have to do "Start Chat".

**Comment by allella** [comment]
@eric1234 @alexdresko @sirbeep 

We have a [spreadsheet to help with future head count and food estimates / expectations](https://docs.google.com/spreadsheets/d/1ddyknPjweYzK-vJ2YWujshVpZGJWo9UVzfldlg8usmc/edit?gid=0#gid=0).

The cost per head is one of the metrics in the sheet.

I'm assuming / encouraging everyone to submit their expenses for reimbursement, and it would be good to know what we spent for adding to this sheet.

Thanks

**Comment by raiderrobert** [comment]
Yup, definitely would be good to know!

I think David already reached out on this, but the Expensify account was
supposed to have been closed down last June

**Comment by allella** [comment]
It should "archived" on Expensify, but it didn't prevent me from using the "Start a Chat" and using the admin@ email.  Sorry, I didn't realize Expensify was being nixed.

@dsiglin were you able to see the receipts I / we uploaded, or do we need to share that through email, Slack, or other medium?

**Comment by raiderrobert** [comment]
We saw them, and he'll be reaching out to you.

We nixed them and switched to doing just checks back in May because they
changed their pricing and wanted $10/mo per user, which seemed outrageously
high for our purposes.

Eric went through the new process, so we thought it was more commonly known.

Sorry for the miss!

**Comment by allella** [comment]
Alright, is there a form or email we should use in the future?  I'll update our issue template with anything related to how we should submit the receipts.

**Comment by raiderrobert** [comment]
I thought Alan had written up something and shared it with you all. But
seems that's not so.

I'll get something written up and share it with you all.
