### ISSUE TITLE
2024 Q1 Event - Speakers and Format

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#3]
### 6:20 - 6:35
Gavin Coyle — 15 mins on [_Addressing Workforce Planning Challenges Through Mentorship_](https://github.com/hackgvl/nights/issues/3#issuecomment-1941392980)
### 6:35 - 6:50
[Paul](https://github.com/avon61002) — 15 mins on _Censorship-resistant P2P Messaging via [Briar](https://briarproject.org/) and the [Local-first Software](https://www.inkandswitch.com/local-first/) Movement_.

#### Breakout Room 1
- Bogdan Kharchenko — 15 mins on [_Data Transfer Objects with PHP, as used by HackGreenville.com_](https://github.com/hackgvl/nights/issues/3#issuecomment-1924039357)
- Jim Ciallella — 5 mins on [_Lean Livin': How the Local Internet Provider Paid Me $6240 / hr_](https://hackgreenville.slack.com/archives/C0420TN6W/p1707330356467909)
- Christina Roberts — 10 mins on [_Volunteer Opportunities w/ Agile Learning Institute_](https://github.com/hackgvl/nights/issues/3#issuecomment-1941551165)

#### Breakout Room 2
- Brian Kennedy — 15 mins on _[You're Doing IaC Wrong](https://github.com/hackgvl/nights/issues/3#issuecomment-1952581442)_
- Jās Eckard —  5 mins on [_Intro to UCLUG and BASH's History Feature_](https://github.com/hackgvl/nights/issues/3#issuecomment-1939712062)
- Pamela Wood Browne —  10 mins on _Intro to Code With The Carolinas and Current Projects_

### Backup / Future Talks
- [Barry Jones](https://github.com/hackgvl/nights/issues/3#issuecomment-1922016402) - (As a backup) Lightning Talk | _Ruby ActionMailbox for Parsing Inbound Emails_
- Luke Kapustka (LukeTech on Slack) on Pros and Cons of 5G Home Internet Service - inspired by a [Feb 2024 Slack thread](https://hackgreenville.slack.com/archives/C0420TN6W/p1708459314090209?thread_ts=1708448544.205969&cid=C0420TN6W)

## Notes
- [The Oct 2023 pilot event speakers and topics are listed on the Meetup event.](https://www.meetup.com/hack-greenville/events/296051672/) 
- The [pilot notes contain potential speakers, and potential future speakers / ideas / topics](https://docs.google.com/document/d/106st3E4nNViZhedZ6N2ZJE9W0J_wvN0-0VmZjQftio0/edit#heading=h.5kzk7h2e7g65).
- We agreed to post a call for speakers and in #random on the Slack and Jim will reach out to people who expressed interest for the pilot event.

## Format
- Pam suggested "[at least one speaker before breaking out into other rooms](https://hackgreenville.slack.com/archives/C0JPADQDD/p1705509800769809?thread_ts=1705507321.527509&cid=C0JPADQDD)"
- Eric suggested we may have the [potential speakers help define the format / time slots](https://hackgreenville.slack.com/archives/C0JPADQDD/p1706284911339419?thread_ts=1705507321.527509&cid=C0JPADQDD).
- Jim suggested a balance would be [a single track speaker of perhaps 20-25 minutes max and the rest of the event as break outs / multi-track](https://hackgreenville.slack.com/archives/C0JPADQDD/p1705509800769809?thread_ts=1705507321.527509&cid=C0JPADQDD).

## Tasks (In-advance)
- [ ] TODO: Setup a web form to gather relevant details from speakers: (doesn't exist, do for Spring 2024 event)
  - Speaker's Name
  - Talk Title
  - Public Link to Slides (optional)
  - Talk Length(s)
  - Needs: video cables, podium, whiteboard, audio speakers, time clock, projector, etc
- [x] Reach out to speakers who have previously expressed interest
- [x] Post a call for speaker / talk submissions in #community-organizers
- [x] If needed, post a call for speaker / talk submissions in #general or #random a week or so after posting in #community-organizers
- [x] Offer lightning talks to organizers of groups which are on hiatus or which have low attendance
- [x] If needed, ask community partners to promote the call for speakers to their relevant audience
- [x] Have a backup speaker for when someone is sick or can’t make it.
- [x] Advise speakers to come with proper video adapters to connect their laptop via HDMI
- [x] TODO Consider grading the talks on skill / knowledge level: newbie, intermediate, advanced and having a mix of different levels
- [x] Connect with speakers to share details (audio / video setup, share Wi-Fi details, time slots, attendee expectations (like expecting people to come and go during the talks), and [where to park and how to enter the building](https://joinopenworks.com/guest-access)
- [x] Ask if speakers need any special equipment, like power cords, whiteboards & markers, podium, audio speakers, time clocks, projector
- [x] Suggest that speakers come early to test Wi-Fi, video, and other connections
- [x] Survey speakers to see if they are interested in a basic Jitsi or Zoom video recording and/or paying for a [more professional edited video option](https://github.com/hackgvl/nights/issues/5)

## Tasks (At the Event Venue)
- [ ] Take a photo of the space before hand so things can be put back where they were
- [ ] Prepare the conference rooms (move the white tables to the empty hall past the men's room at OpenWorks)
- [ ] Position and erase whiteboards
- [ ] Confirm audio / video / internet is working for the presenters
- [ ] Double-check that the presenters brought proper HDMI to Laptop adapters
- [ ] Turn on TVs and set to the correct “source”

**Comment by allella** [comment]
The [speaking schedule is now on Meetup](https://www.meetup.com/hack-greenville/events/299063777/).

We'll announce it in some places tomorrow.

**Comment by allella** [comment]
Speakers,

In preparation for next week, here are presenter-related questions and notes.  Please reply to the questions and let us know if you have any other concerns.

- Please come with proper video adapters to connect your laptop via HDMI if you're planning to use a TV
- @avon61002 and @gavincoyle your talks will be in our round table area and have access to the wall mounted TV with HDMI input
-  @bogdankharchenko @ChristinaDRoberts @sirbeep @chruck @pamelawoodbrowne  @allella will be in either of the [two conference rooms as indicated on the schedule](https://www.meetup.com/hack-greenville/events/299063777/). The conference rooms will have only a rolling TVs with HDMI input cables and one rolling seating-height table, unless you request otherwise (see below)
- Wi-Fi is SSID: _nextonmain_ and Passphrase: _Next@nMain300_ This is a 10 Mpbs / 10 Mbps fiber connection. If you need a faster connection, then reach out to me / Jim in advance
- The event starts at 6 PM. There will be time to setup before your talk starts, but it's always good to test the internet and A/V connections, so it would be wise to arrive early to verify things will work.  Volunteers will be there as early as 4:30 PM, so feel free to come between 4:30 and 6 PM
-  **Please let us know if you have any needs related to the following**:
    - Do you have any audio / video needs in addition to the aforementioned TVs
    - Use of power cords and outlets
    - Whiteboards & markers
    - Podium / lectern (table top)
    - Audio speakers
    - Projector
    - Time clocks (we don't have these, but could setup the timer on a phone, or something similar, if you don't have your own solution)
    - Holler if there's anything else that the host space (_OpenWorks_) would need to provide, or need to know?
- Please expect that attendees may come and go during the talks. We will try to keep any socializing during the talks far enough away to avoid disruption
- Please see _OpenWorks_' notes on [parking and how to enter the building](https://joinopenworks.com/guest-access) through the City's _Richardson Street Parking Garage_
-  Volunteers (@oliviasculley and @jhloman ) will be doing a [basic tri-pod video recording of the events](https://github.com/hackgvl/nights/issues/5).
   - If you would prefer your talk not be recorded and/or posted online, then please let me / Jim know
   - We will likely post these on a HackGreenville channel (yet to be setup) and see if people engage with the video before considering more advanced production.  If you think more advanced recording and post-production work is something future speakers might like as an optional / paid upgrade, then feel free to [drop your thoughts on the video thread](https://github.com/hackgvl/nights/issues/5).
- Volunteer Alan Johnson @nalanj will be taking photos on an iPhone. If you want him to get your "good side", then connect with Alan about any photo-related requests.

**Comment by allella** [comment]
Two other notes.

1) If you haven't already, [please RSVP for the event on Meetup](https://www.meetup.com/hack-greenville/events/299063777/).
2) If you would like to work out of OpenWorks the day of the event, then please reach out to Jim or Pam for more info.

**Comment by sirbeep** [comment]
"If you would like to work out of OpenWorks the day of the event, then please reach out to Jim or Pam for more info." 
hey, that's a good idea.  I should come early to make sure my pot is hot.

**Comment by allella** [comment]
Presenters,

We have over 80 guests registered. With no-shows and walk-ins we'll probably come in somewhere between 65-75 people

To make more room for the Breakout talks, we're going to expand "Room 2" to include both conference rooms by opening up the middle divider wall.

As a result, "Room 1" of the breakouts, which will be @bogdankharchenko @ChristinaDRoberts and me, will use the round table and kitchen area and TV, which is where the single track talks will occur earlier in the schedule.

We'll have a dedicated "Social Lounge" inside OpenWorks for those who choose to socialize during any portion of the talking session, which we expect to help isolate the sound.
