### ISSUE TITLE
2024 Q3 Event - Volunteers

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#31]
See our earlier [_Volunteers_](https://github.com/hackgvl/nights/issues?q=volunteers+in%3Atitle+is%3Aissue) issues for past notes and context.

### Volunteers
- [Food & Drinks](https://github.com/hackgvl/nights/issues?q=food+planning+in%3Atitle+is%3Aissue)
  - Confirmed: [Eric Anderson](https://github.com/eric1234), [Brian Kennedy](https://github.com/sirbeep), [Jim Ciallella](https://github.com/allella), [Austin Moede](https://github.com/TrezmoAustin), [Creighton Magoun](https://github.com/magoun), [Alex Dresko](https://github.com/alexdresko)
  - Unconfirmed / Past: [Joel G.](https://github.com/TwonkyHardware), Sally Anderson
- [Video](https://github.com/hackgvl/nights/issues?q=video+in%3Atitle+is%3Aissue)
  - Confirmed: [Olivia Sculley](https://github.com/oliviasculley)
  - Unconfirmed / Past: [Joey Loman](https://github.com/jhloman), [Matt Thornton](https://github.com/ThorntonMatthewD)
- [Breakdown](https://github.com/hackgvl/nights/issues?q=breakdown+in%3Atitle+is%3Aissue)
  - Confirmed: [Jim Ciallella](https://github.com/allella), [Austin Moede](https://github.com/TrezmoAustin), [Creighton Magoun](https://github.com/magoun), [Jacob Adelberg](https://github.com/jadelbe418), [Joey Loman](https://github.com/jhloman)
  - Unconfirmed / Past: [Zach Robichaud](https://github.com/zach2825), [Bogdan Kharchenko](https://github.com/bogdankharchenko), [Matt Irby](https://github.com/orgs/hackgvl/people/irby), Jack Brackley, [Alex Dresko](https://github.com/alexdresko)
- [Setup / Check-in](https://github.com/hackgvl/nights/issues?q=check-in+in%3Atitle+is%3Aissue)
  - Confirmed: [Violet Kester](https://github.com/violet-kester), [Austin Moede](https://github.com/TrezmoAustin), [Creighton Magoun](https://github.com/magoun), [Joey Loman](https://github.com/jhloman)
  - Unconfirmed / Past: [Jacob Adelberg](https://github.com/jadelbe418), [Zach Robichaud](https://github.com/zach2825), [Bogdan Kharchenko](https://github.com/bogdankharchenko), [Matt Irby](https://github.com/orgs/hackgvl/people/irby), Jack Brackley, [Alex Dresko](https://github.com/alexdresko)
- [Promo Whiteboard](https://github.com/hackgvl/nights/issues?q=whiteboard+in%3Atitle+is%3Aissue)
  - Confirmed: [Jas Eckard](https://github.com/chruck), [Paul](https://github.com/avon61002)
  - Unconfirmed / Past:
- Photos
  - Confirmed: [Pam Wood Browne](https://github.com/pamelawoodbrowne)
  - Unconfirmed / Past: [Alan Johnson](https://github.com/nalanj)
- [Speakers Outreach & Coordination](https://github.com/hackgvl/nights/issues?q=speakers+format+in%3Atitle+is%3Aissue)
  - Confirmed: [Jim Ciallella](https://github.com/allella)
  - Unconfirmed / Past: [Barry Jones](https://github.com/brightball), [Ryan Lanciaux](https://github.com/ryanlanciaux)
 
### Tasks
- [x] Get commitments from volunteers for the upcoming event
- [x] Ask volunteers to RSVP to the event
- [x] Connect with volunteers and share necessary tasks / details with them
- [x] Confirm about with any video recording volunteers
- [x] Communicate with volunteers about when they need to arrive, tasks, and such
- [x] Ask volunteers to raise their hand at the event if they see a speaker or other volunteers with a hand up. This worked well at the Feb 2024 event to interrupt the crowd without having to do so abruptly.
- [x] Communicate with volunteers about where to park to unload and how to get into the building if they arrive before the doorbell is up.

### Offered to Volunteer in the Future

- Ryan MacAllan - (on hiatus) food procurement and/or sponsorship
- Steven Wade - speaker, eventually may be able to helping with some organizing

**Comment by allella** [comment]
@magoun and Austin Moede have been added to the volunteer list.

**Comment by allella** [comment]
@eric1234 @sirbeep do you have have any good potato-related recipes if we do a potato theme? 

We could / should have things that have different proteins, so it doesn't have to be a potato base, per se.

Also, are either of you interested and able to help make food in advance, or prep / setup beforehand?

We could have a mix of things like roasted potatoes, potato soup, potato salad, etc.

**Comment by sirbeep** [comment]
like baked potato topings?

**Comment by sirbeep** [comment]
maquechoux!  I've had cajun cravings lately.

**Comment by allella** [comment]
We could have a baked potatoes option, but I was thinking more of trying to make 50 baked potatoes because of the logistics of cooking that many.

Rather, it could be a diverse range of potato dishes from casseroles to salads to soups, etc.

**Comment by allella** [comment]
We could do "Starch" and call it "Starch Trek"

**Comment by allella** [comment]
Yeah, the logistics of trying to cook and keep 50+ potatoes and then keep them warm for hours feels complicated.  Though, as a first-come first-serve option, I think a potato bar would be a good dish option.

Even if we only had one person cook 20 or so potatoes to go with various other potato dishes.  And / or we could cut them in half so more people could do a smaller portion than an entire potato and use it like a potato boat.

**Comment by allella** [comment]
@eric1234 @sirbeep @alexdresko @TrezmoAustin @magoun @jadelbe418 @chruck @oliviasculley @avon61002 

We'll be doing a free drop-in day at OpenWorks on Tuesday before HG Nights, so volunteers and others are welcome to come early, hang out, and do some work and such.

Holler at me if that's of interest.

**Comment by sirbeep** [comment]
I can do that.. 330 or so I can bring the marque choux to plug up and get warm.

**Comment by magoun** [comment]
I'd be interested in dropping into OW tomorrow after lunch. How do I
sign up for that?

**Comment by oliviasculley** [comment]
I'll most likely be dropping in around lunchtime!
