### ISSUE TITLE
2025 Q1 Event - Food & Drink Planning

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#41]
See our earlier [Food & Drink Planning](https://github.com/hackgvl/nights/issues?q=food+planning+in%3Atitle+is%3Aissue) issues for past notes and context.

### Notes
- The [SnackGreenville document](https://docs.google.com/document/d/1ZBEl61eH4kB6NVHqjrlEgnYyRrfONAyJoQXFcH5muaQ/edit#heading=h.374owrq3m4r2) has recent history, including the prices and amounts used for the HG Nights pilot taco bar.
- For estimating, see our [past Event Attendance, Cancel, No Show, Walk-in, Food Eaten count and ratios doc](https://docs.google.com/spreadsheets/d/1ddyknPjweYzK-vJ2YWujshVpZGJWo9UVzfldlg8usmc/edit?gid=0#gid=0)
- At a past event we had 5 out of 75 attendees indicate a dietary allergy / constraint, including: peanut, pecan, dairy, vegan, and vegetarian concerns. This confirms we should avoid some ingredients, or else have at least one option which will satisfy these types of concerns.

### Menu
- Winter Squash Soop (vegetarian) by @sirbeep
- Red Lentil and Barley Soup (vegan) by @TwonkyHardware
- Italian (cheese) Tortellini Soup w/ Sausage by @rhynodesigns 
- Turkey Parmesan Meatball, Orzo, & Escarole Soup by @allella
- Sides
  - loaf of bread by @rhynodesigns
  - loaf of ciabatta by Rise Bakery @TwonkyHardware 
  - oyster crackers @allella 
- Dessert - Cupcakes (gluten-free & diary-free) by @beetz12

### <span id="ideas">Ideas</span>
- Taco Bar
- Chili Bar
- Sandwich & Sliders Bar
- Potato Bar
- Soup Bar
- Via [Joel G's link to a Reddit Thread](https://github.com/hackgvl/nights/issues/17#issuecomment-2098306696)
  - Brunch Bar
  - Soup Bar
  - Greek / Mediterranean / Mezze Bar - falafel, kofta, kebabs, couscous, tabbouleh, hummus, a bunch of dips, pita, flat bread, olives, etc.
  - Banh Mi Bar
  - Nacho Bar
  - Rice Bowl Bar
  - Tapas Bar - east Indian or Middle Eastern mentioned
  - Asian-style Bar - Teriyaki chicken, Mongolian beef, kung Pao shrimp with lo mein noodles, rice, assorted stir fry veggies
  - Seafood Boil
  - Hot Dog / Sausage Bar
  - Shawarma Bar
  - PBJ - different breads, nut butters, cream cheese, jellies, marshmallow fluff, honey, granola, sliced fruit like strawberries and bananas.
  - Ramen Cup bar - different ramens, soft boiled eggs, mushrooms/veggies/meats, crunchy garnishes like seaweed and crispy onions, and chili oil/sesame oil.
  - Kebab / Skewer Bar
  - BBQ Bar
  - Salad Bar - chopped vegetables, diced avocado, mandarin orange segments, proteins (grated cheese, diced chicken, tuna in oil, lentils, chickpeas, etc), nuts and seeds (sunflower seeds, pepitas, cashews, slivered almonds, etc), and crunchy carb bits like croutons, crushed tortilla chips, fried wonton strips or chow mein noodles. Provide an assortment of quality salad dressings (ex: Asian sesame vinaigrette, Southwest, poppyseed, etc). Aim for a mix of vinaigrettes and creamy dressings such as yogurt-based ones. Try a colourful coleslaw or broccoli slaw base, as well as mixed greens (lettuces)
  - Pasta Bar - 2-3 sauces, chicken, bacon, Italian sausage, pepperoni, assorted cheeses, fresh herbs, steamed broccoli, roasted cauliflower, fresh or sautéed spinach, roasted garlic, buttered breadcrumbs.
  - Pierogies Bar
  - Meatball Bar - greek, asian, italian mentioned
  - Grilled Cheese Bar - not sure this is practical without an legit kitchen
  - Quesadilla Bar - not sure this is practical without an legit kitchen
  - Poutine bar
  
### Food Volunteers
- Confirmed:
  - sirbeep - Brian Kennedy
  - allella - Jim Ciallella
  - TwonkyHardware - Joel Griffith
  - rhynodesigns - Ryan McAllen
  - beetz12 - David He
- Unconfirmed / Past:
  - eric1234 - Eric Anderson
  - alexdresko - Alex Dresko
  - Sally Anderson
  - TrezmoAustin - Austin Moede
  - magoun - Creighton Magoun
  - alexdresko - Alex Dresko]
  - See the [past volunteer](https://github.com/hackgvl/nights/issues?q=volunteers+in%3Atitle+is%3Aissue) threads for more details.

### Hot Plates,  Slow Cookers, Griddle
If we need these to keep things warm, then people offered.
- @allella - 21" x 11" griddle
- @allella - convection oven
- @sirbeep - dual hot plate
- @ThorntonMatthewD - has a couple of slow cookers and a hot plate

### Budget
- Volunteers making food will have a set amount per batch based on the assumed number of guests they will be feeding
- Catering and recipes can typically be cut by 25-40%, as noted in the _SnackGreenville_ document (link above)
- Earlier events have range from 55 to 75 people and not everyone will eat
- Volunteers will be reimbursed by RefactorGVL by check as part of the [Post-Event Tasks and Wrap-up](https://github.com/hackgvl/nights/issues?q=wrap-up+in%3Atitle+is%3Aissue+is%3Aopen).

### Other Food and Desserts
- Toppings
- We have previously done an ice cream sandwich handout about 15-20 minutes before the wrap-up, which requires a freezer at the host location, and about half of the remaining guests tend to partake.
- Beer - Given the liability and added cost, this could remain a volunteer-only perk

### Drinks
- Canned drinks seem to work best and can be recycled at OpenWorks
- Refrigerating the drinks in advance and setting them out in the retail boxes on top of something to absorb condensation seems to work well
- Sparkling Water
- Soda
- Bottled water - we typically provide cups and ice if there's tap water nearby, as there is at OpenWorks

### Tasks (In-advance)
- [x] Put out a call for volunteers
- [x] Dietary or allergy considerations - check to registration form responses
- [x] Instruct volunteers to save any receipts for reimbursement
- [x] Gather recipe ingredients so they can be printed on signs for allergy considerations
- [x] Pay for any prepared food from vendors, either in advance, or at pickup. 
- [x] Check the vendor's hours of operation and pick-up details in advance
- [x] Communicate with volunteers
- [x] Designate a reliable pick-up person and share the pick-up time and details of how to unload the food at the venue
- [x] Determine if drinks can be refrigerated in advance, or if ice and ice bins are needed. - Jim has some 6" tall plastic totes which we've used in the past to ice drinks, and they could be used upon request.
- [x] Determine if any prepared food needs to be refrigerated and confirm there is space - OpenWorks has a large and small refrigerator and there is typically space as long as the refrigerators have been cleaned out of old stuff
- [x] Determine if a freezer is needed and available at the venue. - OpenWorks has a very small freezer, so we'd definitely need to verify space in advance.
- [x] Determine if any convection ovens, hot plates, or insulating pads / coolers are need to keep food warm

- [x] Purchase any food, drinks, plates, napkins, etc in advance
- [x] Purchase volunteer beer and any special volunteer snacks.  A 15 mix pack. like Oskar Blues, is usually enough. 

### Tasks (At the Event Venue)
- [ ] Prepare any food that’s being made on-site
- [ ] Setup food, serving bowls, serving utensils (spoons, tongs). Setup TWO serving utensils for EACH of the main dishes so people can serve from both sides of the bar.
- [ ] Setup bowls / plates at check-in table so people need to check-in before they can eat.
- [ ] Setup napkins, forks / spoons at the end of the food line / upper bar, so people don't have to hold these things while they are making a plate
- [ ] Put forks or spoons in a container, like a mason jar, or small bowl, with the handles facing up / out so people can grab them by the handle.
- [ ] Avoid putting any very hot items directly on the wood counter tops. Use a trivet or other something under hot items. 
- [ ] Move the trash and recycling cans out of the way, but still in a visible spot.
- [ ] Setup a bus bucket and tape sign **(not on drywall)** near the trash cans for dirty utensils / dishes
- [ ] Setup any food heating (ovens, crockpots, hot plates, microwave) or chilling equipment using heavy power cords if needed and try to not put everything on the same circuit, if / when it's possible to tell.
- [ ] Setup drinks, ice, cups on a rolling table near the check-in
  - Cans
    1. [ ] Setup cans - Ideally, keep cans in the cardboard boxes and open 1/2 of one end of the box and put something under the rear of the box so the cans roll forward to the opening for easy grabbing.
    1. [ ] Otherwise, if cans are not cold then it may not be necessary to ice them down in a bin.
    - Note: If icing down the cans, put cans into any bins before pouring the ice on top. Otherwise, it’s very hard to put the cans into shallow ice.
    - Note: Icing cans will often cause condensation, so putting a towel or thick piece of cardboard under the cold bin can help insulate the bottom and limit a wet mess
  - [ ] If using 2-liters, then setup the bottles and cups - (Note: OpenWorks has a bunch of small foam cups in the lower cabinets opposite the bar stools)
  - [ ] (Optionally) Setup clean ice bucket w/ drinking ice & tongs - ideally this isn't needed when serving refrigerated cans
- [ ] When the line forms, encourage people to use both sides of the bar to double the throughput of the main course.

**Comment by allella** [comment]
I've added ideas to the food theme list and food template based on the Reddit thread @TwonkyHardware shared. Check out [the list above](https://github.com/hackgvl/nights/issues/41#user-content-ideas), there are a bunch of new ones.

A few that sound doable, and fun to me, include:

- Brunch Bar
- Soup Bar
- Sausage / Hot Dog Bar

No pressure, but I'm pinging past volunteers for thoughts on the theme and to see who is interested in helping cook and/or prep.

@sirbeep
@eric1234 / Sally
@TwonkyHardware
@alexdresko
@TrezmoAustin
@magoun
@alexdresko

@rhynodesigns you have time or interest in helping with food for this upcoming Feb event?

**Comment by sirbeep** [comment]
Like.. 1 day late.  I just used my last soup bone yesterday to make lentil soup for the cold.  You'll have to settle for grocery beef instead of good farm bones.

**Comment by TwonkyHardware** [comment]
I have a couple of soups.  Just made a good beef & cabbage this week.  If we loosen the language to include stews, I can do a good classic beef and a great red lentil and barley.  Good winter food.

I'm on board with taco bar and sandwiches, too.

**Comment by allella** [comment]
Yeah, I was thinking of soup too.

I'm not opposed to supplementing with prepared foods, or rotating through ideas, but unless / until we run out of volunteer interest, I'd just assume do something unique and fun while we have people excited to show their personal flare.

**Comment by sirbeep** [comment]
soups it is!
Winter Squash Soop
vegetarian, not vegan
Made by SirBeep with:
Love
Butternut, Acorn, etc.. winter squashes.
Onion
Garlic
Cream
Spices

**Comment by rhynodesigns** [comment]
@allella i'm in for helping with Feb meetup.
i can bring soup in a crockpot.
i'll swing by your desk at openupstate next week and chat with you.

**Comment by allella** [comment]
Thanks all.    We've been using the food theme as our sort of Android-style food-based semantic versioning (see [HG Nights page](https://hackgreenville.com/hg-nights)).

At the last event we got corny with the "Starch Trek" theme for potatoes and starches.

We could call this one "Soup-er Bar", but I'm open to even cornier names.

**Comment by alexdresko** [comment]
If I don't type this, I'll be thinking about it all day, like bad song stuck in my head. 

"Soup sup"... like, the shortened "wassup" you would say when greeting someone.  Similar to "soup's up", a common phrase said when dinner is ready. 

I don't even care if you like it. I just needed the thought out of my brain. :)

**Comment by TwonkyHardware** [comment]
SouperMan IV: The Quest for Peas

**Comment by alexdresko** [comment]
I like "Souperman"

**Comment by allella** [comment]
I like it. Maybe something shorter?

SouperMan II: Peas & Love
SouperMan II: World Peas

**Comment by allella** [comment]
I'm thinking of the go-to at my house.

_Turkey Meatball, Orzo, & Escarole Soup._

If nobody has a vegan option, then I may make a small batch of rice soup with a vegan broth instead of chicken broth.

**Comment by allella** [comment]
@TwonkyHardware yes, that sounds great for the vegan option. Thanks.

**Comment by allella** [comment]
@rhynodesigns holler at us with your recipe name and we'll add it to the menu and Meetup event details.

The current commitments are

- Winter Squash Soop (vegetarian) by sirbeep
- Red Lentil and Barley Soup (vegan) by TwonkyHardware
- Turkey Parmesan Meatball, Orzo, & Escarole Soup by allella

**Comment by allella** [comment]
My wife asked if we were having anything else to go along with the soup.   She said cornbread and I thought oyster crackers and saltines.

What other ideas might we add?

Also, @beetz12 may be able to chip in, so adding David to the thread.

**Comment by allella** [comment]
@rhynodesigns are you still in for making 1/4 of the soup for the evening?  If so, we'd like to add your soup choice to the menu, so please share a soup style / name.

**Comment by rhynodesigns** [comment]
Yes sir!

Italian (cheese) Tortellini Soup w/ Sausage
(Also has dairy and gluten)

1 Crockpot and 1 Instapot full.

We’re experimenting baking a loaf of bread, if it turns out, we’ll bring one or two with the soup.

**Comment by allella** [comment]
@rhynodesigns sounds great.

We might buy something simple, like oyster crackers, but fresh bread was also mentioned, so that would be cool if you made some.  And / or we can get some Swamp Rabbit Stecca.

**Comment by TwonkyHardware** [comment]
Tuesday is ciabatta day at Rise.  I'll get a couple of loaves the morning of.

**Comment by allella** [comment]
A few requests leading up to the event that may need your action, so please read below.

1) If you haven't already, please [RSVP on the Meetup page](https://www.meetup.com/hack-greenville/events/305856459/) so we have a good headcount for the food.

2) We list the ingredients for each recipe on a sign so we can avoid any allergy concerns, or other things people might want to know about what's in the dish.  I already have this info for Brian, but @TwonkyHardware @rhynodesigns @beetz12, please share a list of ingredients for your dish.  We don't need a recipe or proportions, just the full list of ingredients

3) Here's the menu we have set. Holler with any tweaks or suggestions.

- Winter Squash Soop (vegetarian) by @sirbeep
- Red Lentil and Barley Soup (vegan) by @TwonkyHardware
- Italian (cheese) Tortellini Soup w/ Sausage by @rhynodesigns
- Turkey Parmesan Meatball, Orzo, & Escarole Soup by @allella
- Sides
- loaf of bread by @rhynodesigns
- loaf of ciabatta by Rise Bakery @TwonkyHardware
- oyster crackers @allella
- Dessert - Cupcakes (gluten-free & diary-free) by @beetz12

**Comment by TwonkyHardware** [comment]
Red lentil and barley soup:

pearled barley
red lentils
leeks
fennel
carrots
cilantro
vegetable broth
garlic
tomato paste
garam masala
turmeric
cinnamon stick
salt
extra-virgin olive oil
lemon juice

optional: lemon wedges, fennel fronds, and bread for serving

**Comment by allella** [comment]
I saw Ryan's reply about a slow cooker and an Instapot.

I'm probably going to do a slow cooker and a soup pot.

I was going to use the griddle we have at OpenWorks as a make-shift hot plate for my pot. It can probably fit a second pot.

Though, if anybody is planning to bring a pot that needs reheating, then perhaps @sirbeep 's double-hot plate would help.

**Comment by allella** [comment]
@rhynodesigns @beetz12 @sirbeep @TwonkyHardware this is a reminder to save receipts for food costs.  They will be needed to submit for reimbursement from RefactorGVL after the event.

Thanks again and holler at me with anything you need.

**Comment by allella** [comment]
The RSVPs are currently at 50 people and we might expect about 60 to 65 people, based on past numbers. 

About 80% to 90% of attendees have eaten food at our events. Unless we get a large jump, we can expect that if each of us makes enough to feed 15 people, then we should be good.

**Does anybody have an issue with making enough of their soup for 15 people?**  My rough guess, I'm figuring the average portion size for a stand-up and eat event like this may be around 10-12 ounces per person.

We'll have smaller 12 oz bowls (good for about 1-1/2 ladles without spilling), so people are encouraged to try more than one soup, and to cut back on waste from folks taking large portions.

Also, please bring a ladle. If you have more than one ladle, please bring it so we can have the food line go on both sides of the counter to speed things up if a line forms.

Any other thoughts or questions?

@sirbeep @rhynodesigns @TwonkyHardware

**Comment by allella** [comment]
@TwonkyHardware @sirbeep @rhynodesigns @beetz12

I'm picking up last minute things at Aldi around 2 PM. Does anybody need me to grab anything?
