### ISSUE TITLE
2025 Q1 Event - Speakers and Format

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#48]
##Notes
- Review our talk submissions that came in through the [official form](https://hackgreenville.com/hg-nights). 
- See earlier [Speakers & Format Planning](https://github.com/hackgvl/nights/issues?q=speakers+format+in%3Atitle+is%3Aissue) issues for other ideas for speakers and past context.
- The [pilot notes contain potential speakers, and potential future speakers / ideas / topics](https://docs.google.com/document/d/106st3E4nNViZhedZ6N2ZJE9W0J_wvN0-0VmZjQftio0/edit#heading=h.5kzk7h2e7g65).

## Confirmed Speakers

- mins  | Speaker Name | Talk Title | Talk Description
- mins  | Speaker Name | Talk Title | Talk Description
- mins  | Speaker Name | Talk Title | Talk Description
- mins  | Speaker Name | Talk Title | Talk Description

## Rough Schedule

6:00 - 6:20 — Food
6:20 - 6:25 — Welcome and Intro to Sponsor
6:25 - 6:35 — TBD
6:35 - 6:40 — Break and Brief Community Announcements
6:40 - 6:55 — TBD
6:55 - 7:10

- Break
- Community Breakout Conversation

7:10 - 7:20 — TBD
7:20 - 7:35 — Break
7:30 - 7:45 — TBD
7:45 - 8:00+ — Social and Ice Cream Bars

## Tasks (In-advance)
- [ ] Reach out to speakers who have previously expressed interest and invite them to fill out the [Talk Submission form](https://forms.gle/gudqeQwpjQmR7QLV6).
- [ ] Post a call for speaker / talk submissions in #community-organizers directing people to fill out the [Talk Submission form](https://forms.gle/gudqeQwpjQmR7QLV6)
- [ ] If needed, post a call for speaker / talk submissions in #general or #random a week or so after posting in #community-organizers
- [ ] Offer lightning talks to organizers of groups which are on hiatus or which have low attendance
- [ ] If needed, ask community partners to promote the call for speakers to their relevant audience
- [ ] Have a backup speaker for when someone is sick or can’t make it.
- [ ] Advise speakers to come with proper video adapters to connect their laptop via HDMI
- [ ] TODO Consider grading the talks on skill / knowledge level: newbie, intermediate, advanced and having a mix of different levels
- [ ] (Jim has a template) Connect with speakers over Slack to share details (audio / video setup, share Wi-Fi details, time slots, attendee expectations (like expecting people to come and go during the talks), video recording, [where to park and how to enter the building](https://joinopenworks.com/guest-access)
- [ ] Ask if speakers need any special equipment, like power cords, whiteboards & markers, podium, audio speakers, time clocks, projector
- [ ] Suggest that speakers come early to test Wi-Fi, video, and other connections
- [ ] Remind speakers to repeat any questions if they have a Q&A so the questions can be heard on the video recording

## Tasks (At the Event Venue)
- [ ] Take a photo of the space before hand so things can be put back where they were
- [ ] Prepare the conference rooms (move the white tables to the empty hall past the men's room at OpenWorks)
- [ ] If opening the partition in the conference room
  - [ ] Get Jim Ciallella to help, or else contact the security desk for help, as the wall requires special know-how and has been damaged in the past by unskilled folks messing with it.
  - [ ] WARN people about putting their fingers in the seams
  - [ ] WARN people to move the TVs away from the wall before folding the wall
- [ ] Position and erase whiteboards
- [ ] Confirm audio / video / internet is working for the presenters
- [ ] Double-check that the presenters brought proper HDMI to Laptop adapters
- [ ] Turn on TVs and set to the correct “source”
- [ ] Remind speakers to test the HDMI and do a dry run to make sure they have what they need
- [ ] Setup podium
- [ ] Turn off any load equipment in / near the room, like white noise systems or HVAC fans

**Comment by allella** [comment]
@eric1234 @pamelawoodbrowne @bogdankharchenko 

We have 12 talk ideas below grouped into three categories: recent submissions by people who haven't spoken, unofficial submissions I noted from Slack threads, and talks from people who have already talked at an HG Nights.

We also have two AI talks in the first bucket.  Do we want to avoid two talks on the same theme at an event?

Do we want to start by reaching out to the new speakers and then roll to the previous speaker list if people in the "new" pool in the order they submitted?  If they can't commit to Feb 25 then roll down the list?

# Talks from New Speakers
- ASO - App Store SEO
- Garbage in, diamonds out: using AI for software development
- Simulating Analog Television on the Web
- Beyond Coding: How Windsurf AI is Making Software Development Accessible to Everyone

# Unofficial Talks for New Speakers Pulled from Slack Threads
- Pros and Cons of 5G Home Internet Service 
- Comparison of Blaze, Addy.io, Firefox Relay, SimpleLogin, DDG Email Protection, Apple's Hide My Email
- Two talks ideas for the same person: 1) VS Code Dev Container & 2) Using ML / AI"

# Talks Submitted by Previous Speakers
- Ruby ActionMailbox for Parsing Inbound Emails
- Creating an SD-WAN starlink/T-Mobile mesh network during Hurricane Helene
- DIY Digitizing Those Closet Hogging Homemade VHS Tapes
- The Elixir Ecosystem
- Lean Livin' - Cheapo Mobile

**Comment by allella** [comment]
Here's a tag cloud of interests from the previous event.

![Image](https://github.com/user-attachments/assets/19c44eff-1777-40b7-962d-2b2252122172)

**Comment by allella** [comment]
Here's a tag cloud of interests from the previous event.

![Image](https://github.com/user-attachments/assets/f8baa9d1-6129-4757-bba7-83906b4d0ce5)

**Comment by pamelawoodbrowne** [comment]
> Do we want to start by reaching out to the new speakers and then roll to the previous speaker list if people in the "new" pool in the order they submitted? If they can't commit to Feb 25 then roll down the list?

Makes sense to me 👍🏻

**Comment by allella** [comment]
Two new speakers have committed.

- 5 mins  | Zach | _Simulating Analog Television on the Web_ | I'll be demoing my hobby project called Television Simulator '99. I wrote it in SvelteKit and Tailwind and it takes advantage of modern CSS tricks and browser features to attempt to simulate a vintage TV set, receiver and cable headend in an easy-to-extend, easy-to-customize way, all while being a static web app.
- 10 mins  | David He | _Beyond Coding: How Windsurf AI is Making Software Development Accessible to Everyone_ | Join us for an eye-opening presentation about Windsurf, a groundbreaking AI-powered tool that's changing how we think about creating software

**Comment by allella** [comment]
Two AI talks committed, but I think they will be sufficiently different as one is about a tool and the other is about a process.  

I didn't hear from Hunter over the weekend and assumed he wasn't going to reply, but he did this morning.

- 15 mins  | Hunter Hodnett | _Garbage In, Diamonds Out: Using AI for Software Development_ | The stochastic nature of generative AI makes it an unwieldy tool in the hands of a novice software engineer. In this talk, I'd like to demonstrate the ways in which my engineering team at Chipp has navigated this issue by grounding the AI with context.

**Comment by allella** [comment]
Forth talk has been confirmed

 10 mins  | Paul Sullivan | _The Elixir Ecosystem_ | High level overview of the Elixir Ecosystem

**Comment by allella** [comment]
Hunter uncommitted from speaking due to an emergency business trip.
