### ISSUE TITLE
2025 Q1 Event - Volunteers

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#52]
See our earlier [Volunteers](https://github.com/hackgvl/nights/issues?q=volunteers+in%3Atitle+is%3Aissue) issues for past notes and context.

### Volunteers
- [Food & Drinks](https://github.com/hackgvl/nights/issues?q=food+planning+in%3Atitle+is%3Aissue)
  - Confirmed: Jim Ciallella, Brian Kennedy, Joel Griffith, Ryan McAllen, David He
  - Unconfirmed / Past: Eric Anderson, Sally Anderson, Alex Dresko, Austin Moede, Creighton Magoun
- [Video](https://github.com/hackgvl/nights/issues?q=video+in%3Atitle+is%3Aissue)
  - Confirmed: Olivia Sculley
  - Unconfirmed / Past: Joey Loman, Matt Thornton
- [Setup](https://github.com/hackgvl/nights/issues?q=check-in+in%3Atitle+is%3Aissue)
  - Confirmed: Matt Irby, Archye Valdez, Bogdan Kharchenko
  - Unconfirmed / Past: Pam Wood Browne, Jacob Adelberg, Zach Robichaud, Jack Brackley, Alex Dresko
- [Check-in Table](https://github.com/hackgvl/nights/issues?q=check-in+in%3Atitle+is%3Aissue)
  - Confirmed: Matt Irby
  - Unconfirmed / Past: Pam Wood Browne, Jacob Adelberg, Violet Kester
- [Promo Whiteboard](https://github.com/hackgvl/nights/issues?q=whiteboard+in%3Atitle+is%3Aissue)
  - Confirmed: Jas Eckard
  - Unconfirmed / Past: 
- Photos
  - Confirmed:
  - Unconfirmed / Past: Violet Kester, Alan Johnson
- [Breakdown](https://github.com/hackgvl/nights/issues?q=breakdown+in%3Atitle+is%3Aissue)
  - Confirmed: Jim Ciallella, Jacob Adelberg, Bogdan Kharchenko
  - Unconfirmed / Past: Zach Robichaud, Matt Irby, Jack Brackley, Alex Dresko 
- [Speakers Outreach & Coordination](https://github.com/hackgvl/nights/issues?q=speakers+format+in%3Atitle+is%3Aissue)
  - Confirmed:
  - Unconfirmed / Past: Barry Jones, Ryan Lanciaux
 
### Tasks
- [x] Get commitments from volunteers for the upcoming event
- [x] Ask volunteers to RSVP to the event
- [x] Connect with volunteers and share necessary tasks / details with them
- [x] Confirm about any special needs for the video recording volunteer(s)
- [x] Communicate with volunteers about when they need to arrive, tasks, and such
- [x] Ask volunteers to raise their hand at the event if they see a speaker or other volunteers with a hand up. This worked well at the Feb 2024 event to interrupt the crowd without having to do so abruptly.
- [x] Communicate with volunteers about where to park to unload and how to get into the building if they arrive before the doorbell is up.

### Offered to Volunteer in the Future

- Ryan MacAllan - (on hiatus) food procurement and/or sponsorship
- Steven Wade - speaker, eventually may be able to helping with some organizing

**Comment by allella** [comment]
@magoun @zach2825 @bogdankharchenko @irby @alexdresko @ryanlanciaux

We could use a hand with set up, breakdown, check-in table, and taking photos for [HG Nights on Feb 25](https://www.meetup.com/hack-greenville/events/305856459/).

Any of you previous volunteers interested and able to chip in?

Thanks

**Comment by irby** [comment]
@allella I am available to help with check-in and breakdown.

**Comment by bogdankharchenko** [comment]
Sure thing
