### ISSUE TITLE
2024 Q1 Event - Volunteers

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#6]
The [pilot event's notes have a volunteer section](https://docs.google.com/document/d/106st3E4nNViZhedZ6N2ZJE9W0J_wvN0-0VmZjQftio0/edit#heading=h.tervj73plqz) with past volunteers. Plus, it includes some people who weren't able to attend the pilot who offered to assist in the future.

### 2024 Q1 Offers to Help
- Food Volunteers - [we have 4 commitments to help with the food](https://github.com/hackgvl/nights/issues/2) - Brian Kennedy, Joel Griffith, Eric Anderson, Jim Ciallella
- Bogdan Kharchenko - ~ 5 PM arrival - [as needed](https://github.com/hackgvl/nights/issues/6#issuecomment-1924042963)
- Jacob Adelberg - arriving around 5:30 - lobby door, setup and breakdown
- Zach Robichaud - offered to help with setup and breakdown - likely will arrive around 5 PM 
- Alan Johnson - event photography
- Jack Brackley - arriving around 5:00 - setup
- Video Recording - Olivia Sculley, Joey Loman, Matt Thornton

### Tasks
- [x] Get commitments from volunteers for the upcoming event
- [x] Ask volunteers to RSVP to the event
- [x] Connect with volunteers and share necessary tasks / details with them
- [x] Confirm about with any video recording volunteers https://github.com/hackgvl/nights/issues/5
- [x] Communicate with volunteers about when they need to arrive, tasks, and such

### Previous / Pilot Volunteers

- Barry Jones - identifying speakers
- Eric Anderson - offered to help with whatever, helping with food prep @ 5PM
- Brian Kennedy - helping with day of food prep @ 5PM
- Alex Dresko - setup / breakdown and bot whispering
- Olivia Sculley - setup & breakdown, check-in, photos, planning
- Pamela Wood Browne - setup & breakdown, check-in, photos, planning
- Jim Ciallella - planning, setup / breakdown and project management
- Ryan Lanciaux - coordinated speakers in Michigan, but offered to help with whatever
- Alan Johnson
- Hunter Hodnett - previously mentioned interest in identifying sponsors
- Pete Broderick - set-up - 5:15 - 5:30
- Jacob Adelberg - lobby greeter, setup - 5:45
- Zach Robichaud - 5:15 - 5:30

### Offered to Volunteer in the Future

- Ryan MacAllan - (on hiatus) food procurement and/or sponsorship
- Steven Wade - speaker, eventually may be able to helping with some organizing

**Comment by allella** [comment]
Setup, Breakdown, Video, & Photo Volunteers,

@bogdankharchenko @nalanj @jadelbe418 @oliviasculley @jhloman @ThorntonMatthewD @zach2825 

Thanks for offering to help at the upcoming HackGreenville Nights on Thursday Feb 29.

- If you haven't already, [please RSVP for the event on Meetup](https://www.meetup.com/hack-greenville/events/299063777/).
- If you would like to work out of _OpenWorks'_ coworking space prior to the event, then please reach out to Jim or Pam for more info.
- The event starts at 6 PM, but attendees will likely show up early, so we'll need to get most tasks done between 5:00 PM and 5:50 PM.
- Some setup task will require volunteers to arrive between 5 PM and 5:30 PM to allow time for setup.  Please share if you're unable to arrive before 5:30 and we can still use help during the event and with breakdown at the end.
- We'll likely start some kitchen clean-up before 8PM. The event officially ends at 8 PM and we can proceed with breakdown, but we expect to allow attendees to mingle after 8 PM.  If you have to leave by a specific time, then please share that time.
- You are welcome to arrive ever earlier in the day and utilize the _OpenWorks_ coworking space for free the day of the event.  If you'd like to do so, then please reach out to me or Pamela.
- I will be in touch with more notes next week about specific tasks for setup and break-down
